### PR TITLE
Fix index too large error in MySQLStore

### PR DESCRIPTION
**Pull request by gmt2001**
Remove unused imports

### CODE REVIEW

**Comment by gmt2001** [comment]
Is there something wrong with this commit?

**Comment by Hackebein** [comment]
I think it's better to display a warning/error if the databse has a wrong charset. I think this is the best solution for future test and support scenarios.

**Comment by gmt2001** [comment]
UTF8MB4 is actually the correct charset to use in modern times.

**Comment by BrandenB** [comment]
I'm going to merge this for now, I hope that it's fully tested.

**Pull request merged**
