### PR TITLE
Added setName method to change discord bot name

### PR DESCRIPTION
**Pull request by CreativeCodeCat**
**Commands:**
* !setname [username]

**Examples:**

image
image
image

**Console log:**

```
[02-27-2018 @ 15:18:35.869 GMT] [DISCORD] [#staff] alixe: !setname HDTVBot
[02-27-2018 @ 15:18:36.127 GMT] [DISCORD] [#staff] [CHAT] <@!79751645986041856>, Bot name updated to: HDTVBot
[02-27-2018 @ 15:18:52.771 GMT] [DISCORD] [#staff] alixe: !setname HDTVBot
[02-27-2018 @ 15:18:52.785 GMT] [ERROR] [misc.js:261] [DISCORD] Unable to change bot name: sx.blah.discord.util.RateLimitException: Rate limit exceeded.
[02-27-2018 @ 15:18:52.821 GMT] [DISCORD] [#staff] [CHAT] <@!79751645986041856>, Bot name was not updated due to an error: Please check Error logs!
[02-27-2018 @ 15:35:23.383 GMT] [DISCORD] [#staff] alixe: !setname
[02-27-2018 @ 15:35:23.393 GMT] [DISCORD] [#staff] [CHAT] <@!79751645986041856>, Usage: !setname [name]
```

**You may delete this entire text from your Pull Request if you so desire. It is acceptable if you leave it in place as well.**

**Anything you would like changed please reply below**

### CODE REVIEW

**Comment by BrandenB** [comment]
Errors from Discord should be handled in the core and not from JavaScript.

**Comment by AlixeAtTwitch** [comment]
ok close this as i have no idea how to do that and send the message as I tried that first and couldnt get the errors to work in the java end

**Comment by CreativeCodeCat** [comment]
So something like this?? otherwise if you dont have the try in the JavaScript to then it will always send the message even if it fails!

Following the same code rules as below.

```
/**
         * @discordcommandpath module enable [path] - Enables any modules in the bot, it should only be used to enable discord modules though.
         */
        if (command.equalsIgnoreCase('module')) {
            if (action === undefined || (subAction === undefined && !action.equalsIgnoreCase('list'))) {
                say(channel, userPrefix(mention) + $.lang.get('discord.misc.module.usage'));
                return;
            }

            if (action.equalsIgnoreCase('enable')) {
                var module = $.bot.getModule(subAction);

                if (module !== undefined) {
                    $.setIniDbBoolean('modules', module.scriptName, true);
                    $.bot.loadScript(module.scriptName);
                    $.bot.modules[module.scriptName].isEnabled = true;

                    var hookIndex = $.bot.getHookIndex(module.scriptName, 'initReady');

                    try {
                        if (hookIndex !== -1) {
                            $.bot.getHook(module.scriptName, 'initReady').handler();
                        }

                        say(channel, userPrefix(mention) + $.lang.get('discord.misc.module.enabled', module.getModuleName()));
                    } catch (ex) {
                        $.log.error('[DISCORD] Unable to call initReady for enabled module (' + module.scriptName + '): ' + ex.message);
                    }
                } else {
                    say(channel, userPrefix(mention) + $.lang.get('discord.misc.module.404', subAction));
                }
            }
```

**Comment by BrandenB** [comment]
$.bot is an object with JavaScript functions, so errors cannot be handled in Java. If we start mixing where errors and handled it gets annoying for me to debug later on. The changeUsername method shouldn't even throw anything according to Discord4J docs.

**Comment by CreativeCodeCat** [comment]
the 2 errors it can throw

```
[02-27-2018 @ 14:54:18.281 GMT] [misc.js:262] [DISCORD] Unable to change bot name: sx.blah.discord.util.DiscordException: Error on request to https://discordapp.com/api/v6/users/@me. Received response code 400. With response text: {"username": ["You are changing your username or Discord Tag too fast. Try again later."]}
[02-27-2018 @ 15:18:52.782 GMT] [misc.js:261] [DISCORD] Unable to change bot name: sx.blah.discord.util.RateLimitException: Rate limit exceeded.
```

**Comment by BrandenB** [comment]
Rate limit exceptions shouldn't be thrown since it can lead to a Discord ban. Please handle it with Discord4J's RequestBuffer method.

**Comment by CreativeCodeCat** [comment]
Im going to close this and remove the pull request and leave it to the people that know what there doing as i can not seem to get this to work :(

**Pull request closed without merging**
