### PR TITLE
Added Discord-To-Twitch linking system

### PR DESCRIPTION
**Pull request by gmt2001**
Uses a basic 2-step linking process to verify ownership of a Twitch account and link it to a Discord account. Requires allowing DM's from the bot on Discord until the linking process is complete.

NOTE: Does not automatically work with Twitch name changes, re-linking is required.

Usage:
```
$.bind('discordCommand', function (event) {
  var senderId = event.getDiscordId();
  var twitchName = $.discord.discordToTwitch(senderId);

  //twitchName now contains the twitch username, just like a normal command event from irc
});
```

### CODE REVIEW

**Comment by BrandenB** [comment]
Making a system like was mentioned before for linking a user’s account with Discord, but the main thing that stopped us from making it now was when Twitch added the ability to change your username. Knowing that, soon we will be trying to move all points and time to user ids and not their actual name, this will probably be done once we finish our TwitchAPIv5 class.

**Here is a bug I found in the code:**
-	Line #83, you’re trying to get the name and discriminator from the variable sender, which does not contain the functions `getName()` and `getDiscriminator()` only `event` does. When running the `!accountlink` command you will get an error right away. This is done in a lot of other places too. 

**Issues:**
-	In some places I see that you’re calling the entire package for the Discord API, you can simply just use `$.discordAPI.` for this. This is done with other things too like `println`.
-	Your code has a mix of single and double quotes most of the current scripts use single quotes, so please follow that. Some variables also don’t match up: https://i.zelakto.tv/Ipe4h82.png
-	The sending DM function you made, I’d rather see that in the `DiscordAPI.java` class than in the scripts, it keeps the API functions all in the same place and makes it less confusing for other people looking at the code or trying to debug issues in the future.
-	Also, you’re storing everything with the users Discord username and discriminator, since users can change their names on Discord their discriminator will also change when that happens, it would be better storing it with their Discord ID since that never changes. Same goes for Twitch usernames, but doing that makes this script useless until we migrate over to the new API.
-	One other thing I want to add is why are you using the temp store? If a user reboots the bot, or his/her pc crashes, etc everything will be lost.


Another note, right now Twitch whispers seem to be broken for a lot users, what I mean by this is that if they don't follow the bot account it cannot whisper them even though the `only allow whispers from users I follow` is not checked, I've tested this on my main account and it works fine but as soon as I move to my alt I don't get any whispers.

Don't feel forced to make these changes, it's completely up to you.

**Comment by gmt2001** [comment]
The TempStore is only used for storing the authentication tokens because they are, by definition, temporary and should be destroyed after 10 minutes or when the bot shuts down, whichever comes first.

Will work on the other points

**Comment by BrandenB** [comment]
Please do some testing. Just ran two commands and noticed two issues.

```
[03-07-2017 @ 18:46:21.411 GMT] [DISCORD] [#admin] scaniatv: !accountlink link
[03-07-2017 @ 18:46:21.432 GMT] [ERROR] [init.js:326] (hook.call, discordCommand, ./discord/core/accountLink.js) InternalError: Cannot convert 1488912984520 to java.lang.Integer (accountLink.js#59)
```


```
[03-07-2017 @ 18:45:33.971 GMT] [DISCORD] [#admin] scaniatv: !accountlink
[03-07-2017 @ 18:45:33.973 GMT] [DISCORD] [#admin] [CHAT] *In order to use this module, please unblock the bot from your Discord DM's.\nIf you have disabled DM's from users in this server, please re-enable it temporarily.*\nTo link your Discord account to your Twitch account, say **!accountlink link**
```

**Comment by gmt2001** [comment]
What is the issue with the second one?

**Comment by BrandenB** [comment]
`\n` is not being replaced with a new line in Discord, sorry, I should of been a bit more specific.

**Comment by BrandenB** [comment]
Did you fully test it?

**Comment by gmt2001** [comment]
Working out a few kinks, got more commits in the pipeline

**Comment by gmt2001** [comment]
Ready to go

**Comment by BrandenB** [comment]
**When just typing `!accountlink` in Twitch chat:**
```
[03-07-2017 @ 20:59:33.222 GMT] scaniatv: !accountlink
[03-07-2017 @ 20:59:33.247 GMT] [ERROR] [init.js:317] (hook.call, command, ./discord/core/accountLink.js) TypeError: Cannot call method "equalsIgnoreCase" of undefined
```
**When using `!points` in Discord:**


**If you just start the bot up and the first command you use in chat is the account link command this happens, only happens with that one.**
```
[03-07-2017 @ 21:02:34.852 GMT] scaniatv: !accountlink link rcWmpjSy
[03-07-2017 @ 21:02:34.881 GMT] [ERROR] [onEvent()@ScriptEventManager.java:114] Failed to dispatch event me.mast3rplan.phantombot.event.irc.channel.IrcChannelUserModeEvent
[03-07-2017 @ 21:02:34.881 GMT] [DISCORD] [@ScaniaTV#6094] [DM] Your Discord account has been successfully linked to **ScaniaTV** on Twitch.
Please note that if you change your name on Twitch, you will have to redo this.
```

**`0` is the default permission for the Caster. In Discord it's for everyone, so I get why that can be confusing:**
```
$.registerChatCommand('./discord/core/accountLink.js', 'accountlink', 0);
```

I think that's most of it, be sure to test again after.

**Comment by gmt2001** [comment]
Fixed 1, 2, and 4.

3 is not related to my stuff

**Comment by BrandenB** [comment]
I just tested with a bunch of other default bot commands and can never get that error to show up. So something with the account link command is causing that event to fail. It will probably show up anytime a moderator types it, if it's their first message being sent to the channel.

**Comment by gmt2001** [comment]
I am unable to reproduce this error with a clean bot

**Comment by BrandenB** [comment]
I did a bit more testing, and the results are odd.

On a fresh bot it works fine without any issues, but however, if I use an older database that error comes up. I tried with my old database, Phantom's database and an old one from like version 2.3.3 that was on my server and they all gave out the same error every time. That being said, there's probably something that has been set in those databases that causes the error when that command is ran. I tried commands that have three parameters like the account link command has, and they did not give out any errors. I tried doing a bit of debugging to find the issue but could not find anything. 

Now about merging, if I merge this someone else will probably run into the same issue once we release our next version or if someone uses the nightly build. Merging something that has an issue and hope that it doesn't happen to anyone else might not be a smart move, since it will probably happen and they will report on the forum and it will have to get fixed one way or another.

If you can find the issue and fix it I'll be happy to merge this since a lot of people were requesting something like this and it saves me the trouble of making it myself. Right now it's getting late here so I'll check back on this tomorrow if i'm not too busy.

Cheers.

**Comment by gmt2001** [comment]
Did you get a stack trace at all in your console when this error occurred? The code shows that your supposed to get one. Also, if you have a copy of the faulty database that you wouldn't mind sending to me on a forums PM that would help.

**Comment by BrandenB** [comment]
It's not printing the stacktrace in the console, but it was writing it in `.logs\core-errors\` and I completely forgot to check those logs. Will send a copy of the db on the forum. 

```
[03-08-2017 @ 03:43:23.507 GMT] [onEvent()@ScriptEventManager.java:114] Failed to dispatch event me.mast3rplan.phantombot.event.irc.channel.IrcChannelUserModeEvent

[03-08-2017 @ 03:43:23.522 GMT] org.mozilla.javascript.EcmaError: TypeError: Cannot find function getName in object admin. (init.js#806)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4053)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2425)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2407)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:83)
	at org.mozilla.javascript.gen.init_js_1._c_anonymous_30(init.js:806)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.gen.init_js_1.call(init.js)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:137)
	at org.mozilla.javascript.InterfaceAdapter$1.run(InterfaceAdapter.java:83)
	at org.mozilla.javascript.Context.call(Context.java:501)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:503)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:86)
	at org.mozilla.javascript.jdk13.VMBridge_jdk13$1.invoke(VMBridge_jdk13.java:132)
	at com.sun.proxy.$Proxy2.handle(Unknown Source)
	at me.mast3rplan.phantombot.script.ScriptEventManager.onEvent(ScriptEventManager.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34)
	at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Now why is that object getting changed to `admin`.. who knows.

**Comment by gmt2001** [comment]
Figured out the actual symptom of the issue. Somehow $.channel is getting corrupted and replaced in that 1 instance with the String name of the Discord channel you used **!accountlink link** in, with the # stripped

**Comment by gmt2001** [comment]
Disabling all Discord scripts except the core ones (as in the default settings) seems to temporarily fix the issue. I am trying to narrow down the offending script now

**Comment by gmt2001** [comment]
Identified the culprit as ./discord/systems/greetingsSystem.js

Working on a fix

**Comment by gmt2001** [comment]
Solved. Someone put a semicolon instead of a comma in [greetingsSystem.js#L72](https://github.com/PhantomBot/PhantomBot/blob/master/javascript-source/discord/systems/greetingsSystem.js#L72) which caused corruption of the global namespace. I'm not sure how but somehow Rhino translated **channel = whatever** to be the same as **$.channel = whatever**, but only when being executed in the global namespace, even though logic says they should be considered as 2 unique global namespaces

**Comment by BrandenB** [comment]
guess it's good to go now, merging it. thanks.

**Pull request merged**
