### PR TITLE
Reworked StatusphraseSystem with webpanel support

### PR DESCRIPTION
**Pull request by agaertner**
I polished my statusphrase system for Phantombot in order to make it a feature of phantombot.

[What's this?](https://community.phantombot.tv/topic/99/status-phrase-system-keep-your-stream-to-appear-fresh)
- Adds a phrase to your broadcast title and changes it in a specific time intervall. This is cool if you want your stream to appear new and fresh in the broadcasts list.

This new code.
- Supports the webpanel.
- Supports language files.
- Pretty & stabilized.

### CODE REVIEW

**Comment by phantomindex** [comment]
maybe some default phrases?

**Comment by agaertner** [comment]
There are ([statusphrasesPanel.js line 262](https://github.com/PhantomBot/PhantomBot/pull/903/files#diff-d8f1eb863017c9e766e6094876aad6eeR261)), but I made it so that they are not pushed by default. There is a button called "Random" which puts a random phrase inside the 'add phrase' inline form so it can be added by pushing the 'Submit' button. (If generated phrase is liked.)

**Comment by IllusionaryOne** [comment]
Multiple issues identified.  Cannot accept this change.

**Comment by agaertner** [comment]
What are those issues? I am pretty sure I sorted all out with latest commit.
In my forked branch I also added @commandpath

(not shown here due to closed.)

**Comment by viktordimov** [comment]
Hi Tybald. I managed to make your StatusPhrase System work but there's no way (that I am capable of) for me to make the Panel and the system communicate. I noticed PB 3 has changed paths, so I'd like to know if you could help me out by updating the script or telling me how to do it myself.

**Pull request closed without merging**
