### PR TITLE
- Fixed hook call

### PR DESCRIPTION
**Pull request by BrandenB**

### CODE REVIEW

**Comment by Leosaba73** [comment]
How can add this fix into my stable version of 2.3.7.1 version of phantombot?

**Comment by kojitsari** [comment]
Manually edit the file that was fixed, with the fix. Or wait for the nightly that will be compiled in a few hours and use the nightly.

**Comment by Leosaba73** [comment]
Can you take me an example of modifing steps and hint me what program i do
use for editing is ?

Il 23 Lug 2017 9:54 AM, "kojitsari" <notifications@github.com> ha scritto:

**Comment by kojitsari** [comment]
https://community.phantombot.tv/t/modifying-a-stock-phantombot-module/411

**Comment by Leosaba73** [comment]
Thanks you more

Il 23 Lug 2017 10:19 AM, "kojitsari" <notifications@github.com> ha scritto:

https://community.phantombot.tv/t/modifying-a-stock-phantombot-module/411

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PhantomBot/PhantomBot/pull/1569#issuecomment-317237075>,
or mute the thread

**Pull request merged**
