### PR TITLE
Revert "Karlito83 restructure"

### PR DESCRIPTION
**Pull request by IllusionaryOne**
Reverts PhantomBot/PhantomBot#2092

I made the mistake of not testing this change prior to commit because it looked ok.  PhantomBot no longer launches:

```
[morpheus] /opt/iobot
illusion% ./launch.sh
[01-03-2019 @ 19:45:45.464 GMT] The working directory is: /usr/local/opt/iobot
[01-03-2019 @ 19:45:45.468 GMT] Detected Java 1.8.0_102 running on Linux 4.8.13-100.fc23.x86_64 (amd64)
[01-03-2019 @ 19:45:45.532 GMT] Enabling Script Reloading
[01-03-2019 @ 19:45:45.534 GMT]
[01-03-2019 @ 19:45:45.534 GMT] PhantomBot Version: 2.4.2
[01-03-2019 @ 19:45:45.534 GMT] Build Revision: a50268a
[01-03-2019 @ 19:45:45.535 GMT] Creator: mast3rplan
[01-03-2019 @ 19:45:45.535 GMT] Developers: PhantomIndex, Kojitsari, ScaniaTV, Zackery (Zelakto) & IllusionaryOne
[01-03-2019 @ 19:45:45.535 GMT] https://phantombot.tv/
[01-03-2019 @ 19:45:45.535 GMT]
^C[morpheus] /opt/iobot

Stacktrace:
[01-03-2019 @ 12:48:04.720 MST] java.lang.NullPointerException
        at tv.phantombot.PhantomBot.<init>(PhantomBot.java:512)
        at tv.phantombot.PhantomBot.main(PhantomBot.java:1341)
```
Reverting.

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
The master branch launches fine after revert:

```
[morpheus] /opt/iobot
illusion% ./launch.sh
[01-03-2019 @ 19:52:45.657 GMT] The working directory is: /usr/local/opt/iobot
[01-03-2019 @ 19:52:45.661 GMT] Detected Java 1.8.0_102 running on Linux 4.8.13-100.fc23.x86_64 (amd64)
[01-03-2019 @ 19:52:45.663 GMT] Enabling Script Reloading
[01-03-2019 @ 19:52:45.665 GMT]
[01-03-2019 @ 19:52:45.665 GMT] PhantomBot Version: 2.4.2
[01-03-2019 @ 19:52:45.666 GMT] Build Revision: 5653f79
[01-03-2019 @ 19:52:45.666 GMT] Creator: mast3rplan
[01-03-2019 @ 19:52:45.666 GMT] Developers: PhantomIndex, Kojitsari, ScaniaTV, Zackery (Zelakto) & IllusionaryOne
[01-03-2019 @ 19:52:45.666 GMT] https://phantombot.tv/
[01-03-2019 @ 19:52:45.666 GMT]
[01-03-2019 @ 12:52:46.189 MST] YouTubeSocketServer accepting connections on port: 27003
[01-03-2019 @ 12:52:46.240 MST] TEST PanelSocketServer accepting connections on port: 27004
[01-03-2019 @ 12:52:46.315 MST] HTTP server accepting connection on port: 27000
[01-03-2019 @ 12:52:47.572 MST] Validated Twitch CHAT (oauth) OAUTH Token.
[01-03-2019 @ 12:52:47.573 MST] Validated Twitch API (apioauth) OAUTH Token.
[01-03-2019 @ 12:52:47.871 MST] Authenticated with Twitter API
```

**Comment by CreativeCodeCat** [comment]
this is why i do screen shots and logs like requested

**Comment by Karlito83** [comment]
I'm sorry. I found the error and corrected it.

**Comment by CreativeCodeCat** [comment]
You might need to merge the main build back to yours and fix anything that breaks and resubmit as there was changes to a few of the files in the last 12 hours the init.js being one of them that i know of

**Comment by Karlito83** [comment]
Thank you for the advice. Merging the main build track back in my branch would have deleted my changes. Reverting the revert and apply the fix afterwards was an easyer way to reapply my changes.

**Pull request merged**
