### PR TITLE
databaseCommand.js - Debugging plugin for end-user.

### PR DESCRIPTION
**Pull request by agaertner**
A quick debugging plugin for phantombot.

Why?

When a developer (core or plugin dev) makes changes to his/her database tables or keys he/she can tell the users to call !dbedit [action] [args] to clear **old obsolete** keys or tables so they don't conflict with the db changes in a new release of his/her script.
- It will warn the user if table/key exists and prompt him to reply with 'yes' or 'no' before a change is made permanent.
- The user has 20 seconds to reply and cannot call another subcommand for the duration or before a valid respond is given.

### CODE REVIEW

**Comment by BrandenB** [comment]
this is already a debug command in the core.

**Comment by IllusionaryOne** [comment]
While this is a neat addition, this is something never meant to be ran from Chat.  It is meant to only be executed from the Console.  It could be dangerous to let Moderators run such commands, this is why you have Production DBAs in the real world that understand the data sets and relationships.

**Comment by agaertner** [comment]
I could make an exception array (a blacklist) including all the core tables that can't be used in !dbedit.

So it would just be a means for plugin makers.

**Comment by phantomindex** [comment]
Honestly, I don't see the point. If you want this for your bot then that is fine. We don't think it should be a main part of the bot. 

My reason is if someone who's new wanted to see what those commands do without looking, it may change something they never intended to change. 

I also must say the same for GW2 module, it's too specific, our bot is meant for the general public, not to specialize on one game.

I would like to one day have a page where plugins such as yours could be added to a list where anyone could download and throw in their bot, similar to Bukkit for Minecraft.

**Pull request closed without merging**
