### PR TITLE
Fixing the issue with duplicates in $.users

### PR DESCRIPTION
**Pull request by Caricatore**
Need to run an additional check before adding users from the new "ircChannelUsersUpdate" event to remove the chance of appearing duplicates in the user's list

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
I had coded something a little bit like this previously to dedup the users (although in a loop) which was changed.  There was a change as well from another developer that seems to have been reverted at some point prior to this change.

As this change was not the same as the previous committed change, can you by chance show test results?  The logic looks great, but we do hope to see test results to see that the change was checked over (unit tested at a minimum).

**Comment by Caricatore** [comment]
To be honest, I am not a programmer and don't have tools or knowledge to unit test it. I simply make these changes in Notepad and then test it on live stream :) So I can show you points logs (that are dependent on users list) before and after this change was done in the code.

Before: https://drive.google.com/open?id=1Ym44SWDZ5mvgXNgUpeLDpMdvX0XjalP2
After: https://drive.google.com/open?id=1kZAyZ7onhJ9FA8UTFqcH1LnVr4g2flm7

**Comment by CreativeCodeCat** [comment]
Below is my before and after test i was getting the odd duplacate before addign this change and now i dont!

Before:

> [01-23-2018 @ 21:36:33.679 GMT] Executed RareCandies payouts. Users: hdtvbot(1), hdtvbot(1), streamelements(1), logviewer(1)
> [01-23-2018 @ 22:36:33.732 GMT] Executed RareCandies payouts. Users: hdtvbot(1), hdtvbot(1), streamelements(1), logviewer(1)
> [01-23-2018 @ 23:36:33.836 GMT] Executed RareCandies payouts. Users: hdtvbot(1), hdtvbot(1), streamelements(1), logviewer(1), alixe(1), alixe(1)

After:

> [01-24-2018 @ 19:36:53.869 GMT] Executed RareCandies payouts. Users: hdtvbot(1), logviewer(1), streamelements(1), alixe(1)
> [01-24-2018 @ 20:36:54.087 GMT] Executed RareCandies payouts. Users: hdtvbot(1), logviewer(1), streamelements(1), alixe(1)
> [01-24-2018 @ 21:36:54.183 GMT] Executed RareCandies payouts. Users: hdtvbot(1), logviewer(1), streamelements(1), alixe(11), justbothelp(1)
> [01-24-2018 @ 22:36:54.211 GMT] Executed RareCandies payouts. Users: hdtvbot(1), logviewer(1), streamelements(1), alixe(1)
> [01-24-2018 @ 23:36:54.270 GMT] Executed RareCandies payouts. Users: hdtvbot(1), logviewer(1), streamelements(1), alixe(1)

**Comment by IllusionaryOne** [comment]
@Caricatore you nailed it though.  A unit test is basically just verifying that the core functionality works and that the application doesn't just crater.  You also provided logs to verify that you did unit test (you watched it and made sure it did what you wanted it to do).  Welcome to development 😄 

@ScaniaTV I am good with this change and the logs -- if you approve, go ahead and merge it, or let me know and I will.

**Comment by IllusionaryOne** [comment]
Thanks @AlixeAtTwitch for verifying as well!

**Comment by BrandenB** [comment]
I'm okay with it too, so merging! Thanks!

**Pull request merged**
