### PR TITLE
Add missing Twitch clip command vars

### PR DESCRIPTION
**Pull request by jaredcat**
Heres proof of work on Twitch: 
image

and on Discord:
image

### CODE REVIEW

**Comment by dungi** [comment]
Uh nice. Currently the (title) is not working in Twitch Chat. Will this fix this also?

**Comment by jaredcat** [comment]
@dungi yes, check the first screenshot

**Comment by dungi** [comment]
Ah the screenshot was so small, didn't saw that. Nice. Then I can create a new feature after that. Cause I needed the title to check, if the user created the clip accidentally or not. Cause this happen 2-3 times a stream. If the title is the same as the stream title, I can prevent printing the clips to discord and the chat and manually post them to discord, if the content is valid.

Thanks for your work.

**Comment by jaredcat** [comment]
@dungi you should make that a toggleable feature. Users are often just too lazy or just don't know to create a title.  
We curate every single clip on our channel and there are a lot of legitimate clips with the stream title (yes a lot of them are bad or accidental but not all)

**Comment by dungi** [comment]
Yes that was the plan.

**Review by gmt2001 — APPROVED** [review]

**Pull request merged**
