### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by ghost**
- Added two lang strings for easier translation into other languages

### CODE REVIEW

**Comment by vesturo** [comment]
will it still work with Translations made bevore the change or do i need to Rebuild the Translation?

**Comment by ghost** [comment]
Vesturo, developers approve PLs of each other for a few hours, my first PL been hanging for a week. So at the moment I’m not sure they are interested in the third party contributions. If someone will approve my PLs, I'll let you know what you need to change in the German translation. P.S. I asked the developers to consider my three pull requests as a whole thing, because I still haven't figured out why some commits join the old PL and some don't.

**Comment by vesturo** [comment]
That would be awsome, thank you!

**Comment by BrandenB** [comment]
Looks good to me, will let @IllusionaryOne and @Zackery check and merge.

We always let most developers look at pull requests before merging so nothing gets missed.

**Comment by Zackery** [comment]
Looks good here.

**Comment by IllusionaryOne** [comment]
Normally I do not approve without test results.  Since this is language only, I am going to assume that it was unit tested though and results are available?  I make very few exceptions to this rule.  I also *ignore* pull requests most of the time without them. Please let me know if the pull_request_template is not displaying when you submit a pull request so I can check that.  Part of that message is:

You must provide test results for your change.  If test results are not provided we will do one of two things. We will ask you for test results or we will just reject the change.  Test results convince us that you performed a unit test and verified your change.

We reserve the right to reject a change for any reason at all.  Typically, we will provide a reason but if we do not, that is at our discretion.  There are some reasons for which we will reject changes, other than the ones given above (but they will be repeated):

- Code style does not match.
- Incompatible license/improper use of license of third party software/API.
- No test results.
- Potential performance issues.
- Design changes that go against the core design philosophy.
- Items with potential to spam or consume the outgoing message queue.
- Poorly architected items.
- Item is supported in chat but no update for the Control Panel.
- Any command that would violate the Twitch Terms of Service or the Terms of Service of any provider.

**Pull request closed without merging**
