### PR TITLE
Edit Web Panel to change cursor on some items

### PR DESCRIPTION
**Pull request by DarckCrystale**
- In left navbar, default cursor on active link
- In body, default cursor on active header

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
Please attach screen shots showing the test results, that the panel is still functioning properly and looks the same.  This is in the list of items that are required else we will reject a PR.

> You must provide test results for your change. If test results are not provided we will either, ask you for test results or just reject the change.

**Comment by DarckCrystale** [comment]
Left menu, after edit:
capture du 2018-01-22 01-30-24

Accordion menu, after edit:
capture du 2018-01-22 01-37-21

The home page, after edit:
image

**Comment by itsDave1** [comment]
It's bad practice to make any link, regardless of state, into a default cursor. The navbar link, even when active, should stay a pointer.

**Comment by CreativeCodeCat** [comment]
@DarckCrystale totaly agree a link is a link regardless if its active or not

**Comment by IllusionaryOne** [comment]
I am looking to @Collussus to comment on this.  I believe the mouse pointer should turn into the "hand" in these instances (cursor: pointer).

**Comment by itsDave1** [comment]
Correct @IllusionaryOne. It should be cursor: pointer.

**Comment by IllusionaryOne** [comment]
@DarckCrystale if you would like to change the cursor style and show a quick screenshot (we love unit tests) then I believe we are good to go.

**Comment by DarckCrystale** [comment]
Ok @IllusionaryOne! I'll change it and make a screenshot :smiley: 

@Collussus for information at this moment, when the link is active, the cursor is a `text` one :slightly_smiling_face:

**Comment by IllusionaryOne** [comment]
Updates?  If not, is ok.

**Pull request closed without merging**
