### PR TITLE
Changed discord twitter feed

### PR DESCRIPTION
**Pull request by CreativeCodeCat**
Set the discord twitter feed to be embeded 

Example of the change:
image

NOTE: The image in the footer is the streamers twitch image! as i couldnt find the twitter icon that wasnt https://twitter.com/favicon.ico and ico files dont work in discord itself

**You may delete this entire text from your Pull Request if you so desire. It is acceptable if you leave it in place as well.**

### CODE REVIEW

**Comment by BrandenB** [comment]
Maybe adding the text from the `withAuthorName` to the lang file would be a good idea, because i'm sure someone will ask. Also, changing `"` to `'`. Anyway, after that I am fine with it. I will let @IllusionaryOne look at it and merge if he's okay with it!

**Comment by CreativeCodeCat** [comment]
added withAuthorName to the discord lang file so it doesnt change the twitch one

**Comment by IllusionaryOne** [comment]
Can remove the commented out code.  This is git, we can look at history. :-)   Do that, I merge.  Cheers.

**Comment by BrandenB** [comment]
Merging since IO is alright with this and the changes requested have been made. Thanks!

**Pull request merged**
