### PR TITLE
Made console classes final and essentially static 

### PR DESCRIPTION
**Pull request by gmt2001**
Removed instances of classes
Made logTimestamp constructor final

I ran usage checks and global searches against all instance() methods for the Console package and determined that they aren't used, which is good since all methods were static anyway. I therefore removed the instance() methods and variables.

I also made them all final classes (prevents extending/subclassing) and added a private constructor to logTimestamp.

This should shave a sliver of memory usage off the bot, as well as shaving a sliver of load off the GC since it wont have to check them.

As an aside, I also fixed my author attribution lines in 3 of the files to use my online name instead of my real name.

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
As of late we have had PRs from several folks that caused issues that we had to troubleshoot, test, and fix.  As such, at one point in our Discord channel I made the comment that we would like to see demonstrations of tests presented before merging changes.  Please provide:

- Demonstrations of the affected systems still functioning.
- Screenshots from the preferred Java Profiler showing the memory reduction.

Please keep in mind that this is not a personal attack or us being rude, we are simply trying to reduce the amount of time that we spend potentially testing and resolving issues.  This is exactly the practice that I go through with my development team at work with all PRs into our code base as well - demonstrate that unit tests (and even a little bit more) were performed.

**Comment by gmt2001** [comment]
Did a heap dump with JMC and interestingly enough either the GC or the compiler had actually already figured out what was going on and removed the instances, so there is either no memory gain to be had here, or it will be resolved almost instantly at startup and is, either way, not worth attempting to measure.

I still submit this patch as a minor code cleanup.

Output tests from patched bot

```
[12-24-2017 @ 05:42:43.769 GMT] gmt2001bot ready!
[12-24-2017 @ 05:43:01.215 GMT] gmt2001: test
[12-24-2017 @ 05:43:27.950 GMT] [DISCORD] [#general] gmt2001: !setstream https://www.twitch.tv/gmt2001/ Creative
[12-24-2017 @ 05:43:27.956 GMT] [ERROR] [init.js:308] (hook.call, discordChannelCommand, ./discord/core/misc.js) JavaException: java.lang.IllegalArgumentException: Stream URL must be a twitch.tv url.
save
[12-24-2017 @ 05:43:39.860 GMT] [CONSOLE] Executing save
debugon
[12-24-2017 @ 05:46:38.124 GMT] [CONSOLE] Executing debugon: Enable Debug Mode
test
[12-24-2017 @ 05:46:41.053 GMT] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event ConsoleInputEvent
[12-24-2017 @ 05:46:41.053 GMT] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event CommandEvent
debugoff
[12-24-2017 @ 05:46:43.224 GMT] [CONSOLE] Executing debugoff: Disable Debug Mode
[12-24-2017 @ 05:46:43.224 GMT] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event ConsoleInputEvent
```

Heap Analysis from official stable build

**Comment by BrandenB** [comment]
Since it doesn't really change anything, I don't see much of a point, someone with a custom core could be using this as well. Once @IllusionaryOne comes back I'll talk more about it with him. As for your author lines, I would merge that part for sure.

**Comment by BrandenB** [comment]
Will merge this, even though it doesn't really change anything performance wise.

**Pull request merged**
