### PR TITLE
Uniformize file paths in the dev env installation guide.

### PR DESCRIPTION
**Pull request by DarckCrystale**
Minor change not affecting the bot (only a .md file was edited).

### CODE REVIEW

**Comment by CreativeCodeCat** [comment]
the ./ isnt needed as its telling you to get the file not the path

**Comment by DarckCrystale** [comment]
@JustAlixe l26, you have `./development-resources/watchers.xml` with a `./` and it's also a file.

**Comment by IllusionaryOne** [comment]
In the IDEs for this documentation, you would select `build.xml` and not `./build.xml`.  Technically, it is the same, but, in the GUI it is not presented with the leading `./`.

image

I cannot speak to the items that I did not add, but I believe I committed the original instructions for build.xml.  The adjustment probably should be on the other paths -- but, I cannot speak to the other tool sets, only Eclipse.

**Comment by IllusionaryOne** [comment]
So, should the other `./` be removed? I believe that is the case. @ScaniaTV any thoughts? It is documentation, not code.

**Comment by BrandenB** [comment]
Unless it's actually an issue with some IDEs, I don't see a point, no.  Up to you if you want to merge @IllusionaryOne.

**Comment by IllusionaryOne** [comment]
I am fine with closing this out and going in and changing the documentation to not have any leading `./`.  Closing.

**Pull request closed without merging**
