### PR TITLE
Added support for defining a section when performing dbquery requests…

### PR DESCRIPTION
**Pull request by gmt2001**
… through the HTTP API

I defined a variable here to replace the hard-coded section parameter strings that defaults to an empty string, which will provide the same behavior/response as before, however, the user can define a *section* GET parameter to override it and retrieve any section they want from the requested table.

I had to change keyExists to use the Full DataStore API method *HasKey* as part of this implementation.

I will post the tests in a reply here once I have them available for you.

### CODE REVIEW

**Comment by gmt2001** [comment]
For this test I used the phantombot_updates table since it is already populated with a bunch of data. I hand-modified rows 1-3 to have a *section* of **Alpha**, 4 & 5 to have **Bravo** and 6 to have **Charlie** for the purposes of this test.

Bot startup

> [04-21-2019 @ 00:48:37.926 GMT] The working directory is: C:\Users\garym\OneDrive\Documents\NetBeansProjects\phantombot-new\dist\PhantomBot-3.0.0
> [04-21-2019 @ 00:48:37.930 GMT] Detected Java 1.8.0_201 running on Windows 10 10.0 (amd64)
> [04-21-2019 @ 00:48:38.004 GMT]
> [04-21-2019 @ 00:48:38.005 GMT] PhantomBot Version: 3.0.0
> [04-21-2019 @ 00:48:38.005 GMT] Build Revision: a7748bf7
> [04-21-2019 @ 00:48:38.005 GMT] Creator: mast3rplan
> [04-21-2019 @ 00:48:38.006 GMT] Developers: PhantomIndex, Kojitsari, ScaniaTV, Zackery (Zelakto) & IllusionaryOne
> [04-21-2019 @ 00:48:38.006 GMT] https://phantombot.tv/
> [04-21-2019 @ 00:48:38.006 GMT]
> [04-21-2019 @ 00:48:38.400 GMT] YouTubeSocketServer accepting connections on port: 25003
> [04-21-2019 @ 00:48:38.408 GMT] PanelSocketServer accepting connections on port: 25004
> [04-21-2019 @ 00:48:38.426 GMT] HTTP server accepting connection on port: 25000
> [04-21-2019 @ 00:48:38.427 GMT]
> [04-21-2019 @ 00:48:39.238 GMT] Loaded module: core/misc.js (Enabled)
> [04-21-2019 @ 00:48:39.254 GMT] Loaded module: core/jsTimers.js (Enabled)
> [04-21-2019 @ 00:48:39.328 GMT] Loaded module: core/updates.js (Enabled)
> [04-21-2019 @ 00:48:39.454 GMT] Loaded module: core/chatModerator.js (Enabled)
> [04-21-2019 @ 00:48:39.469 GMT] Loaded module: core/fileSystem.js (Enabled)
> [04-21-2019 @ 00:48:39.792 GMT] Loaded module: core/lang.js (Enabled)
> [04-21-2019 @ 00:48:39.797 GMT] Loaded module: core/commandPause.js (Enabled)
> [04-21-2019 @ 00:48:39.818 GMT] Loaded module: core/logging.js (Enabled)
> [04-21-2019 @ 00:48:39.834 GMT] Loaded module: core/commandRegister.js (Enabled)
> [04-21-2019 @ 00:48:39.842 GMT] Loaded module: core/whisper.js (Enabled)
> [04-21-2019 @ 00:48:39.855 GMT] Loaded module: core/commandCoolDown.js (Enabled)
> [04-21-2019 @ 00:48:39.861 GMT] Loaded module: core/keywordCoolDown.js (Enabled)
> [04-21-2019 @ 00:48:39.870 GMT] Loaded module: core/gameMessages.js (Enabled)
> [04-21-2019 @ 00:48:39.886 GMT] Loaded module: core/patternDetector.js (Enabled)
> [04-21-2019 @ 00:48:39.920 GMT] Loaded module: core/permissions.js (Enabled)
> [04-21-2019 @ 00:48:39.938 GMT] Loaded module: core/streamInfo.js (Enabled)
> [04-21-2019 @ 00:48:39.967 GMT] Loaded module: core/timeSystem.js (Enabled)
> [04-21-2019 @ 00:48:39.988 GMT] Loaded module: core/initCommands.js (Enabled)
> [04-21-2019 @ 00:48:40.008 GMT] Loaded module: core/panelCommands.js (Enabled)
> [04-21-2019 @ 00:48:40.040 GMT] Validated Twitch CHAT (oauth) OAUTH Token.
> [04-21-2019 @ 00:48:40.075 GMT] Loaded module: commands/customCommands.js (Enabled)
> [04-21-2019 @ 00:48:40.086 GMT] Loaded module: commands/deathctrCommand.js (Disabled)
> [04-21-2019 @ 00:48:40.099 GMT] Loaded module: commands/dualstreamCommand.js (Enabled)
> [04-21-2019 @ 00:48:40.109 GMT] Validated Twitch API (apioauth) OAUTH Token.
> [04-21-2019 @ 00:48:40.109 GMT] Loaded module: commands/highlightCommand.js (Disabled)
> [04-21-2019 @ 00:48:40.120 GMT] Loaded module: commands/lastseenCommand.js (Enabled)
> [04-21-2019 @ 00:48:40.127 GMT] Loaded module: commands/nameConverter.js (Enabled)
> [04-21-2019 @ 00:48:40.138 GMT] Loaded module: commands/streamCommand.js (Enabled)
> [04-21-2019 @ 00:48:40.154 GMT] Loaded module: commands/topCommand.js (Disabled)
> [04-21-2019 @ 00:48:40.162 GMT] Loaded module: games/8ball.js (Disabled)
> [04-21-2019 @ 00:48:40.189 GMT] Loaded module: games/adventureSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.202 GMT] Loaded module: games/gambling.js (Disabled)
> [04-21-2019 @ 00:48:40.219 GMT] Loaded module: games/killCommand.js (Disabled)
> [04-21-2019 @ 00:48:40.237 GMT] Loaded module: games/random.js (Disabled)
> [04-21-2019 @ 00:48:40.245 GMT] Loaded module: games/roll.js (Disabled)
> [04-21-2019 @ 00:48:40.258 GMT] Loaded module: games/roulette.js (Disabled)
> [04-21-2019 @ 00:48:40.272 GMT] Loaded module: games/slotMachine.js (Disabled)
> [04-21-2019 @ 00:48:40.287 GMT] Loaded module: handlers/bitsHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.294 GMT] Loaded module: handlers/clipHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.304 GMT] Loaded module: handlers/dataServiceHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.321 GMT] Loaded module: handlers/donationHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.328 GMT] Loaded module: handlers/emotesHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.341 GMT] Loaded module: handlers/followHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.351 GMT] Loaded module: handlers/gameScanHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.363 GMT] Loaded module: handlers/hostHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.377 GMT] Loaded module: handlers/keywordHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.389 GMT] Loaded module: handlers/panelHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.405 GMT] Loaded module: handlers/raidHandler.js (Enabled)
> [04-21-2019 @ 00:48:40.419 GMT] Loaded module: handlers/streamElementsHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.448 GMT] Loaded module: handlers/subscribeHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.459 GMT] Loaded module: handlers/tipeeeStreamHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.491 GMT] Loaded module: handlers/twitterHandler.js (Disabled)
> [04-21-2019 @ 00:48:40.500 GMT] Loaded module: handlers/wordCounter.js (Disabled)
> [04-21-2019 @ 00:48:40.510 GMT] Loaded module: systems/auctionSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.527 GMT] Loaded module: systems/audioPanelSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.543 GMT] Loaded module: systems/bettingSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.558 GMT] Loaded module: systems/cleanupSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.569 GMT] Loaded module: systems/greetingSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.592 GMT] Loaded module: systems/noticeSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.618 GMT] Loaded module: systems/pointSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.627 GMT] Loaded module: systems/pollSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.640 GMT] Loaded module: systems/queueSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.653 GMT] Loaded module: systems/quoteSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.679 GMT] Loaded module: systems/raffleSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.690 GMT] Loaded module: systems/ranksSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.704 GMT] Loaded module: systems/ticketraffleSystem.js (Disabled)
> [04-21-2019 @ 00:48:40.772 GMT] Loaded module: systems/youtubePlayer.js (Disabled)
> [04-21-2019 @ 00:48:40.901 GMT]
> [04-21-2019 @ 00:48:40.903 GMT] For support please visit: https://community.phantombot.tv
> [04-21-2019 @ 00:48:40.903 GMT]
> [04-21-2019 @ 00:48:40.910 GMT] Connecting to Twitch WS-IRC Server (SSL) [irc-ws.chat.twitch.tv]
> [04-21-2019 @ 00:48:41.621 GMT] Connected to gmt2001@irc-ws.chat.twitch.tv (SSL)
> [04-21-2019 @ 00:48:41.913 GMT] Channel Joined [#gmt2001]
> [04-21-2019 @ 00:48:42.138 GMT] gmt2001 ready!

Result of **http://localhost:25000/dbquery?table=updates&tableExists&webauth=token**

>{"table":{"table_name":"updates","exists":true}}

Result of **http://localhost:25000/dbquery?table=updates&keyExists=installedv2&webauth=token**

> {"table":{"table_name":"updates","key":"installedv2","keyExists":true}}

^ This is an existing bug related to the query we use for HasKey that I just noticed, caused by the `if (section.Length() > 0)` block in https://github.com/PhantomBot/PhantomBot/blob/master/source/com/gmt2001/datastore/SqliteStore.java#L785

Result of **http://localhost:25000/dbquery?table=updates&section=Alpha&keyExists=installedv2&webauth=token**

> {"table":{"table_name":"updates","key":"installedv2","keyExists":true}}

Result of **http://localhost:25000/dbquery?table=updates&section=Bravo&keyExists=installedv2&webauth=token**

> {"table":{"table_name":"updates","key":"installedv2","keyExists":false}}

Result of **http://localhost:25000/dbquery?table=updates&section=Bravo&getKeys&webauth=token**

> {"table":{"table_name":"updates","keylist":[{"key":"installedv2.0.7"},{"key":"installedv2.0.7.2"}]}}

Result of **http://localhost:25000/dbquery?table=updates&section=Charlie&getAllRows&webauth=token**

> {"table":{"table_name":"updates","results":[{"key":"installedv2.0.8","value":"true"}]}}

Result of **http://localhost:25000/dbquery?table=updates&getAllRows&webauth=token**

> {"table":{"table_name":"updates","results":[{"key":"installedv2","value":"true"},{"key":"installedv2.0.5","value":"true"},{"key":"installedv2.0.6","value":"true"},{"key":"installedv2.0.7","value":"true"},{"key":"installedv2.0.7.2","value":"true"},{"key":"installedv2.0.8","value":"true"},{"key":"installedv2.0.9","value":"true"},{"key":"installedv2.1.0","value":"true"},{"key":"installedNewBot","value":"true"},{"key":"installedv2.1.1","value":"true"},{"key":"installedv2.3s","value":"true"},{"key":"installedv2.3.3ss","value":"true"},{"key":"installedv2.3.5ss","value":"true"},{"key":"installedv2.3.5.1","value":"true"},{"key":"installedv2.3.5.2","value":"true"},{"key":"installedv2.3.5.3","value":"true"},{"key":"installedv2.3.6","value":"true"},{"key":"installedv2.3.6ss","value":"true"},{"key":"installedv2.3.6b","value":"true"},{"key":"installedv2.3.7b","value":"true"},{"key":"installedv2.3.9","value":"true"},{"key":"installedv2.3.9.1","value":"true"},{"key":"installedv2.3.9.1b","value":"true"},{"key":"installedv2.4.0","value":"true"},{"key":"installedv2.4.1","value":"true"},{"key":"installedv2.4.2.1","value":"true"}]}}

^ Again a bug I just discovered due to same if statement being used in multiple DataStore methods.

All test results are as expected (after accounting for the existing DataStore bug)

I might submit a PR for the DataStore bugs later on a separate branch

**Comment by gmt2001** [comment]
Usage Notes

Because of the way the GET parameters are parsed in HttpServerCommon.handleDBQuery, you MUST define the *section* parameter in the URL BEFORE the desired query. ie. *getAllRows&section=Alpha* will ignore *section* because of parse order, but *section=Alpha&getAllRows* will work as expected.

I am currently working on fixing 1 bug where adding *section* with either a blank value or as a standalone (no =) parameter will cause an empty response with no status code

**Comment by gmt2001** [comment]
Bug is fixed and was caused by a hidden NullPointerException when attempting to access `keyValue[1]` when it did not exist (due to there being no value in the GET parameter)

I also noticed that the *table* GET parameter was read in such a way that it too would fall victim to this hidden NullPointerException so I included a fix for that too

This PR is now ready for review

**Comment by BrandenB** [comment]
This looks good to me, going to let @IllusionaryOne review it and merge if he is fine with it.

**Comment by IllusionaryOne** [comment]
Sorry for delay, had business travel (leaving again this week!)

**Pull request merged**
