### PR TITLE
Karlito83 fix restructure

### PR DESCRIPTION
**Pull request by Karlito83**
I reverted the revert and applied the fix for the problem. Sorry for the trouble.

Here the startup log. Please tell me if I should provide more information.
```
[01-03-2019 @ 21:28:51.281 GMT] The working directory is: /home/ronny/git/phantombot/PhantomBot/dist/build
[01-03-2019 @ 21:28:51.284 GMT] Detected Java 1.8.0_152 running on Linux 4.18.0-13-generic (amd64)
[01-03-2019 @ 21:28:51.353 GMT] 
[01-03-2019 @ 21:28:51.353 GMT] PhantomBot Version: 2.4.2
[01-03-2019 @ 21:28:51.353 GMT] Build Revision: 53c6eabd
[01-03-2019 @ 21:28:51.353 GMT] Creator: mast3rplan
[01-03-2019 @ 21:28:51.354 GMT] Developers: PhantomIndex, Kojitsari, ScaniaTV, Zackery (Zelakto) & IllusionaryOne
[01-03-2019 @ 21:28:51.354 GMT] https://phantombot.tv/
[01-03-2019 @ 21:28:51.354 GMT] 
[01-03-2019 @ 21:28:51.543 GMT] YouTubeSocketServer accepting connections on port: 25003
[01-03-2019 @ 21:28:51.546 GMT] PanelSocketServer accepting connections on port: 25004
[01-03-2019 @ 21:28:51.559 GMT] HTTP server accepting connection on port: 25000
[01-03-2019 @ 21:28:51.560 GMT] 
[01-03-2019 @ 21:28:52.211 GMT] Loaded module: core/misc.js (Enabled)
[01-03-2019 @ 21:28:52.219 GMT] Loaded module: core/jsTimers.js (Enabled)
[01-03-2019 @ 21:28:52.284 GMT] Loaded module: core/updates.js (Enabled)
[01-03-2019 @ 21:28:52.386 GMT] Validated Twitch API (apioauth) OAUTH Token.
[01-03-2019 @ 21:28:52.435 GMT] Loaded module: core/chatModerator.js (Enabled)
[01-03-2019 @ 21:28:52.457 GMT] Loaded module: core/fileSystem.js (Enabled)
[01-03-2019 @ 21:28:52.746 GMT] Loaded module: core/lang.js (Enabled)
[01-03-2019 @ 21:28:52.754 GMT] Loaded module: core/commandPause.js (Enabled)
[01-03-2019 @ 21:28:52.766 GMT] Validated Twitch CHAT (oauth) OAUTH Token.
[01-03-2019 @ 21:28:52.780 GMT] Loaded module: core/logging.js (Enabled)
[01-03-2019 @ 21:28:52.789 GMT] Loaded module: core/commandRegister.js (Enabled)
[01-03-2019 @ 21:28:52.797 GMT] Loaded module: core/whisper.js (Enabled)
[01-03-2019 @ 21:28:52.808 GMT] Loaded module: core/commandCoolDown.js (Enabled)
[01-03-2019 @ 21:28:52.814 GMT] Loaded module: core/keywordCoolDown.js (Enabled)
[01-03-2019 @ 21:28:52.821 GMT] Loaded module: core/gameMessages.js (Enabled)
[01-03-2019 @ 21:28:52.830 GMT] Loaded module: core/patternDetector.js (Enabled)
[01-03-2019 @ 21:28:52.865 GMT] Loaded module: core/permissions.js (Enabled)
[01-03-2019 @ 21:28:52.882 GMT] Loaded module: core/streamInfo.js (Enabled)
[01-03-2019 @ 21:28:52.900 GMT] Loaded module: core/timeSystem.js (Enabled)
[01-03-2019 @ 21:28:52.916 GMT] Loaded module: core/initCommands.js (Enabled)
[01-03-2019 @ 21:28:52.929 GMT] Loaded module: core/panelCommands.js (Enabled)
[01-03-2019 @ 21:28:52.945 GMT] Loaded module: games/slotMachine.js (Disabled)
[01-03-2019 @ 21:28:52.950 GMT] Loaded module: games/8ball.js (Disabled)
[01-03-2019 @ 21:28:52.956 GMT] Loaded module: games/random.js (Disabled)
[01-03-2019 @ 21:28:52.965 GMT] Loaded module: games/roulette.js (Disabled)
[01-03-2019 @ 21:28:52.973 GMT] Loaded module: games/killCommand.js (Disabled)
[01-03-2019 @ 21:28:52.996 GMT] Loaded module: games/adventureSystem.js (Disabled)
[01-03-2019 @ 21:28:53.008 GMT] Loaded module: games/roll.js (Disabled)
[01-03-2019 @ 21:28:53.018 GMT] Loaded module: games/gambling.js (Disabled)
[01-03-2019 @ 21:28:53.033 GMT] Loaded module: systems/ranksSystem.js (Disabled)
[01-03-2019 @ 21:28:53.049 GMT] Loaded module: systems/pollSystem.js (Disabled)
[01-03-2019 @ 21:28:53.062 GMT] Loaded module: systems/noticeSystem.js (Disabled)
[01-03-2019 @ 21:28:53.070 GMT] Loaded module: systems/auctionSystem.js (Disabled)
[01-03-2019 @ 21:28:53.085 GMT] Loaded module: systems/bettingSystem.js (Disabled)
[01-03-2019 @ 21:28:53.093 GMT] Loaded module: systems/cleanupSystem.js (Disabled)
[01-03-2019 @ 21:28:53.108 GMT] Loaded module: systems/audioPanelSystem.js (Disabled)
[01-03-2019 @ 21:28:53.119 GMT] Loaded module: systems/quoteSystem.js (Disabled)
[01-03-2019 @ 21:28:53.186 GMT] Loaded module: systems/youtubePlayer.js (Disabled)
[01-03-2019 @ 21:28:53.195 GMT] Loaded module: systems/greetingSystem.js (Disabled)
[01-03-2019 @ 21:28:53.216 GMT] Loaded module: systems/pointSystem.js (Disabled)
[01-03-2019 @ 21:28:53.226 GMT] Loaded module: systems/ticketraffleSystem.js (Disabled)
[01-03-2019 @ 21:28:53.238 GMT] Loaded module: systems/queueSystem.js (Disabled)
[01-03-2019 @ 21:28:53.254 GMT] Loaded module: systems/raffleSystem.js (Disabled)
[01-03-2019 @ 21:28:53.260 GMT] Loaded module: commands/highlightCommand.js (Disabled)
[01-03-2019 @ 21:28:53.266 GMT] Loaded module: commands/topCommand.js (Disabled)
[01-03-2019 @ 21:28:53.271 GMT] Loaded module: commands/lastseenCommand.js (Enabled)
[01-03-2019 @ 21:28:53.279 GMT] Loaded module: commands/dualstreamCommand.js (Enabled)
[01-03-2019 @ 21:28:53.285 GMT] Loaded module: commands/deathctrCommand.js (Disabled)
[01-03-2019 @ 21:28:53.289 GMT] Loaded module: commands/nameConverter.js (Enabled)
[01-03-2019 @ 21:28:53.357 GMT] Loaded module: commands/customCommands.js (Enabled)
[01-03-2019 @ 21:28:53.366 GMT] Loaded module: commands/streamCommand.js (Enabled)
[01-03-2019 @ 21:28:53.376 GMT] Loaded module: handlers/ignoreHandler.js (Enabled)
[01-03-2019 @ 21:28:53.384 GMT] Loaded module: handlers/gameScanHandler.js (Enabled)
[01-03-2019 @ 21:28:53.397 GMT] Loaded module: handlers/tipeeeStreamHandler.js (Disabled)
[01-03-2019 @ 21:28:53.420 GMT] Loaded module: handlers/subscribeHandler.js (Disabled)
[01-03-2019 @ 21:28:53.433 GMT] Loaded module: handlers/donationHandler.js (Disabled)
[01-03-2019 @ 21:28:53.442 GMT] Loaded module: handlers/dataServiceHandler.js (Enabled)
[01-03-2019 @ 21:28:53.451 GMT] Loaded module: handlers/wordCounter.js (Disabled)
[01-03-2019 @ 21:28:53.485 GMT] Loaded module: handlers/twitterHandler.js (Disabled)
[01-03-2019 @ 21:28:53.496 GMT] Loaded module: handlers/keywordHandler.js (Enabled)
[01-03-2019 @ 21:28:53.507 GMT] Loaded module: handlers/streamElementsHandler.js (Disabled)
[01-03-2019 @ 21:28:53.517 GMT] Loaded module: handlers/raidHandler.js (Enabled)
[01-03-2019 @ 21:28:53.525 GMT] Loaded module: handlers/followHandler.js (Disabled)
[01-03-2019 @ 21:28:53.537 GMT] Loaded module: handlers/hostHandler.js (Disabled)
[01-03-2019 @ 21:28:53.543 GMT] Loaded module: handlers/clipHandler.js (Enabled)
[01-03-2019 @ 21:28:53.550 GMT] Loaded module: handlers/panelHandler.js (Enabled)
[01-03-2019 @ 21:28:53.572 GMT] [ERROR] [addHook()@init.js:254] Failed to register hook "gameWispChange" since there is no such event.
[01-03-2019 @ 21:28:53.572 GMT] [ERROR] [addHook()@init.js:254] Failed to register hook "gameWispBenefits" since there is no such event.
[01-03-2019 @ 21:28:53.572 GMT] [ERROR] [addHook()@init.js:254] Failed to register hook "gameWispSubscribe" since there is no such event.
[01-03-2019 @ 21:28:53.572 GMT] [ERROR] [addHook()@init.js:254] Failed to register hook "gameWispAnniversary" since there is no such event.
[01-03-2019 @ 21:28:53.574 GMT] Loaded module: handlers/gameWispHandler.js (Enabled)
[01-03-2019 @ 21:28:53.580 GMT] Loaded module: handlers/emotesHandler.js (Enabled)
[01-03-2019 @ 21:28:53.586 GMT] Loaded module: handlers/bitsHandler.js (Disabled)
[01-03-2019 @ 21:28:53.633 GMT] 
[01-03-2019 @ 21:28:53.633 GMT] For support please visit: https://community.phantombot.tv
[01-03-2019 @ 21:28:53.633 GMT] 
[01-03-2019 @ 21:28:53.640 GMT] Connecting to Twitch WS-IRC Server (SSL) [irc-ws.chat.twitch.tv]
[01-03-2019 @ 21:28:54.497 GMT] Connected to ************@irc-ws.chat.twitch.tv (SSL)
[01-03-2019 @ 21:28:54.766 GMT] Channel Joined [#************]
[01-03-2019 @ 21:28:55.017 GMT] ************ ready!
^[[B^C[01-03-2019 @ 21:29:23.455 GMT] ************ is shutting down...
[01-03-2019 @ 21:29:23.455 GMT] Stopping all events and message dispatching...
[01-03-2019 @ 21:29:23.458 GMT] Terminating the Twitch channel follower cache...
[01-03-2019 @ 21:29:23.458 GMT] Terminating all script modules...
[01-03-2019 @ 21:29:23.463 GMT] Saving all data...
[01-03-2019 @ 21:29:23.463 GMT] Shutting down all web socket servers...
[01-03-2019 @ 21:29:23.463 GMT] HTTP server closing down on port 25000 with 5 second delay.
[01-03-2019 @ 21:29:23.657 GMT] Connection to Twitch WS-IRC was closed...
[01-03-2019 @ 21:29:28.466 GMT] HTTP server stopped on port 25000
Waiting for everthing else to shutdown... 1 
[01-03-2019 @ 21:29:33.468 GMT] Closing the database...
[01-03-2019 @ 21:29:33.529 GMT] ************ is exiting.
```

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
When I get home I will go ahead and also check it out and run it.  Thanks for the screenshot and for making the update too!

**Comment by IllusionaryOne** [comment]
I also tested the commands to update the bot configuration file to make sure that the properties were still properly handled.

**Comment by IllusionaryOne** [comment]
This tests out locally and I have spot checked differences between the branches after merge.

**Comment by Karlito83** [comment]
Thank you for merging. :)

**Pull request merged**
