### PR TITLE
Update permissions.js

### PR DESCRIPTION
**Pull request by CreativeCodeCat**
Just a few fixes :)

1. Fixed vipMessageStart = 'the vips of this channel are: ' as this message should be lower case
```
chat .vips
[05-08-2019 @ 12:54:05.650 BST] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event ConsoleInputEvent
[05-08-2019 @ 12:54:05.651 BST] [CHAT] .vips
[05-08-2019 @ 12:54:05.653 BST] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event CommandEvent
[05-08-2019 @ 12:54:05.885 BST] [DEBUG] [onNotice()@TwitchWSIRCParser.java:479] Message from jtv (NOTICE): The VIPs of this channel are: jamesmurf, questgodd.
```
2. Added novipMessageStart = 'this channel does not have any vips' this will detect if there is no vips then will delete the file and remove any vips from the bot

```
chat .vips
[05-08-2019 @ 13:12:43.979 BST] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event ConsoleInputEvent
[05-08-2019 @ 13:12:43.979 BST] [CHAT] .vips
[05-08-2019 @ 13:12:43.981 BST] [DEBUG] [onEvent()@ScriptEventManager.java:77] Dispatched event CommandEvent
[05-08-2019 @ 13:12:44.215 BST] [DEBUG] [onNotice()@TwitchWSIRCParser.java:479] Message from jtv (NOTICE): This channel does not have any VIPs.
```

### CODE REVIEW

**Comment by BrandenB** [comment]
Looks good, I'm okay with it will let @IllusionaryOne check it out and merge if he's okay with it.

**Comment by IllusionaryOne** [comment]
I am merging, but asking a related question.  Is the message different for other regions?  I thought we had a talk in Discord about it being different depending upon location - even the English version being different between two regions?

**Comment by CreativeCodeCat** [comment]
i think after it was removed for the normal irc of /mods or /vips it went with that standard message across all but i may be wrong

**Comment by BrandenB** [comment]
`I thought we had a talk in Discord about it being different depending upon location - even the English version being different between two regions?`

This is only true on the website.

**Pull request merged**
