### PR TITLE
Update ignorebots.txt

### PR DESCRIPTION
**Pull request by lordfloofen**
added a handful of welcome and unwelcome lurk bots I've seen in my chat.

links/reasoning for putting them on the list:
ub3rb0t - not well known on Twitch as you have to contact the owner directly to have it added but still a bot
p0sitivitybot - https://www.reddit.com/r/Twitch/comments/9fe95v/please_put_in_a_way_to_remove_random_bots_that/
v_and_k - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
virgoproz - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
host_giveaway - https://twitch.uservoice.com/forums/297558-general/suggestions/19429897-kick-unwanted-users-bots-from-channel-completely comment
slocool - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
p0lizei_ - https://twitch.uservoice.com/forums/297558-general/suggestions/19429897-kick-unwanted-users-bots-from-channel-completely comment
bananennanen - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
norkdorf - https://www.reddit.com/r/Twitch/comments/9n0nip/ways_to_remove_some_channel_bots/
kingnosebleed - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/e47k6sc?utm_source=share&utm_medium=web2x
apricotdrupefruit - https://www.reddit.com/r/Twitch/comments/9fe95v/please_put_in_a_way_to_remove_random_bots_that/
n3td3v - https://twitch.uservoice.com/forums/297558-general/suggestions/19429897-kick-unwanted-users-bots-from-channel-completely comment
cogwhistle - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
skinnyseahorse - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/e4i5ddo?utm_source=share&utm_medium=web2x
not47y - https://www.reddit.com/r/Twitch/comments/9fe95v/please_put_in_a_way_to_remove_random_bots_that/
activeenergy - https://twitch.uservoice.com/forums/297558-general/suggestions/19429897-kick-unwanted-users-bots-from-channel-completely comment
stayhealthybot - see https://twitch.tv/stayhealthybot
decafsmurf - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
lanfusion - https://www.reddit.com/r/Twitch/comments/96sxsy/can_we_talk_about_bots_is_it_possible_to_start/
foxyboynet - https://www.reddit.com/r/Twitch/comments/7gtj2v/beware_of_this_malicious_bot_which_is_spreading/

**Please read, especially if your first time contributing to PhantomBot:**

Thank you for contributing to PhantomBot! Hopefully you followed the code style guide:
https://github.com/PhantomBot/PhantomBot/blob/master/CODESTYLE.md

If you added in code from a third party, it must have a license that is compatible with PhantomBot.  If it is not, we will reject the merge request.  The development team takes this very seriously.  If you add in access to an API and PhantomBot would use that API improperly, we will reject the merge request.  Again, the development team takes this very seriously.

You must provide test results for your change.  If test results are not provided we will do one of two things. We will ask you for test results or we will just reject the change.  Test results convince us that you performed a unit test and verified your change.

We reserve the right to reject a change for any reason at all.  Typically, we will provide a reason but if we do not, that is at our discretion.  There are some reasons for which we will reject changes, other than the ones given above (but they will be repeated):

- Code style does not match.
- Incompatible license/improper use of license of third party software/API.
- No test results.
- Potential performance issues.
- Design changes that go against the core design philosophy.
- Items with potential to spam or consume the outgoing message queue.
- Poorly architected items.
- Item is supported in chat but no update for the Control Panel.
- Any command that would violate the Twitch Terms of Service or the Terms of Service of any provider.

You are not to harass the development team if a pull request is rejected.  You may discuss and argue why you disagree with a rejection.  We do ask that you stay professional and amicable in your argument and discussion.

All pull requests will be reviewed by at least two PhantomBot developers. Please be patient while two developers take the time to do so.  We understand that this adds time to an approval, but it is to ensure that the development team is not missing anything.

**You may delete this entire text from your Pull Request if you so desire. It is acceptable if you leave it in place as well.**

### CODE REVIEW

**Comment by CreativeCodeCat** [comment]
zanekyber is not a bot that is a streamer he just happened to lurk in alot of channels using his chrome stick for his TV well he is streaming

**Comment by lordfloofen** [comment]
removed zanekyber

**Comment by IllusionaryOne** [comment]
Being that this is just a list and Dakoda already vetted/reviewed it, I am fine with merging unless there are any concerns from anyone else on the team.

**Comment by BrandenB** [comment]
My only concern with this list is that the logic to check if a user is a bot uses a for loop, so if this list becomes long enough it could slow things down.
I'm pretty sure this list was original made for people to add bots that are in their channels only, and not a global list of bots. I would be fine with providing a global list of bots for people to use though.

**Comment by IllusionaryOne** [comment]
Do we want to move the code (not in this PR but in another one) to change from a list to a lookup table?

**Comment by dualznz** [comment]
Moving the code to a table in the DB would allow the creation of a region on the dashboard to add / remove bots & or users.
Thus would be more economic for new users to phantombot

**Comment by gmt2001** [comment]
> 
> 
> My only concern with this list is that the logic to check if a user is a bot uses a for loop, so if this list becomes long enough it could slow things down.
> I'm pretty sure this list was original made for people to add bots that are in their channels only, and not a global list of bots. I would be fine with providing a global list of bots for people to use though.

FYI: The for loop is only being used to load the ignorebots.txt file and to wipe points/time from bots upon initial load or saving changes to the list. Regular isTwitchBot lookups are done as an Associative Array lookup

`    function isTwitchBot(username) {
        return botList[username] !== undefined;
}`

**Comment by BrandenB** [comment]
I saw a comment by @gmt2001, I guess it got deleted, but this was changed so it is no longer a for-loop for the isTwitchBot function. Will merge, might look into a lookup table later on.

**Pull request merged**
