### PR TITLE
Added getLogo

### PR DESCRIPTION
**Pull request by CreativeCodeCat**
img

**You may delete this entire text from your Pull Request if you so desire. It is acceptable if you leave it in place as well.**

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
Illustrate a test of the change working, as indicated in the submission guidelines.

**Comment by CreativeCodeCat** [comment]
ummm thats what the screen shot is.... 
also its the code you helped with with for getting the logo to start with 

```
$.consoleLn("Getting image for dakoda..." + $.getLogo('dakoda'));

[03-13-2018 @ 02:03:43.460 GMT] Getting image for dakoda...https://static-cdn.jtvnw.net/jtv_user_pictures/ea4124c1-d97e-46b3-88c7-ccf8174cdc2c-profile_image-300x300.png
```

**Comment by IllusionaryOne** [comment]
I could not tell where the screenshot came from.  Is that in Discord or something?  To provide background, I manage a team of software engineers where I work and one of the policies we have is to always provide clear test results, including logs.  It makes the life of the developer that has to code review and accept the change easier.  Especially since some of our batch processing can take 5 days to complete :-)

The log message helps a lot.  That is what I was hoping for.

Thanks!

@ScaniaTV I accept, needs your approval.

**Comment by BrandenB** [comment]
Looks good to me, merging.

**Pull request merged**
