### PR TITLE
PhantomBot for Java 11

### PR DESCRIPTION
**Pull request by gmt2001**
This PR updates PhantomBot to run on Java 11.0.4.

This post will detail the changes and any explanations that may be necessary. Test results will be in a separate post below. If an explanation is missing or unclear, let me know and I will get it for you.

:white_check_mark: New Features:
:arrow_right: Updated to OracleJDK11 (64-bit only)
:arrow_right: ARM (Raspberry Pi) supports OpenJDK (32-bit and 64-bit)
:arrow_right: Linux supports OpenJDK if you are on 32-bit
:arrow_right: All 64-bit Windows, Linux, and macOS editions now come with a copy of Java 11, no extra installs needed
:arrow_right: Added automatic builds whenever a `git push` is made to the `edge` branch with GitHub Actions.

This is an optional feature I added since I got into the GitHub Actions beta. If desired, one can create a branch called `edge` in the repo. Whenever something is pushed to `edge`, GitHub Actions will first run a CI build with `ant test` on all platforms (Windows, macOS, and Linux). If all 3 builds succeed, it will then go back to Linux and do a clean build for distribution, posting the build in the Artifacts menu. You can see the results of this by following the instructions in the _Download It_ section below.

The workflow also supports branches whose names start with `edge-` so that you could potentially have a main `edge` branch, and then a few separate edge branches for features being developed in parallel. Thus the main edge branch could be where all those parallel features are merged for combined testing, while separate testing of the individual features by themselves are on the other branches.

This is a great way to setup a rapidly changing edge build for community members who may be helping you test some changes, and has the added advantage over the current nightly build server of triggering automatically with a push by any member of the team with write access to the repo. This also sets the repo up in case some required automated testing is desired to be added later. This can complement the nightly builds as being a rapid testing platform, with the nightly builds either being left as-is, or moved to a weekly schedule.
:arrow_right: Added CI test builds for all pushes and PRs with GitHub Actions on all platforms (Windows, macOS, Linux)

:cyclone: Changed:
:arrow_right: Internally moved libraries to a Maven-based dependency management system to keep them consistent and easier to update (see `Apache Ivy` section below)
:arrow_right: Upgraded Discord4J to the 3.0.x series. I did everything necessary to keep the external interfaces of DiscordAPI and DiscordUtil the same. Only the items listed in _Known Issues_ should need to be changed in custom scripts
:arrow_right: Optimized all DataStore types with connection pooling, try-with-resources, and a few improved SQL queries. All DataStore types are now quite fast, to the point where the slowest database, H2, can still UPSERT `26,384` viewers entries in `phantombot_time` in an average of `998.125ms` vs `252.625ms` for SQLite
:arrow_right: Fixed memory leaks in DataStore, especially SqliteStore. This used to be evident by sitting the bot in an empty channel and watching the memory usage tick up over time and never drop, even when forcing GC calls. It became more pronounced when we upgraded to Java 11, but thanks to the above changes to connection pooling and try-with-resources, which include using try-with-resources to close connection objects at the end of each method, the memory leak is completely gone.
:arrow_right: Fixed the Ping/Pong timer for detecting when the Twitch WSIRC link has gone down. There seemed to be various oddities in timing with this that could cause it to get into a race condition with itself (Connection lost, connection established, pong not received-drop connection, repeat)
:arrow_right: Some minor memory reductions by not instantiating unused Singletons
➡️ Updated launchers to provide platform-specific commands for installing OpenJDK to ARM and x86 Linux installations, as well as unsupported OS version warnings (works on RHEL, Fedora, and Debian based OSes)
➡️ Replaced most of the license files in `resources/licenses`. One of the features of Apache Ivy is that it can generate an HTML report file of the dependencies it downloads which includes their license information, so I only included explicit license files for PhantomBot and the 1 new class I imported into the project from another GitHub repo
➡️ Updated main class to output build type. I updated the main class to put the value of the `-Dbuild_type` parameter on the end of the version line, so we can more easily tell what kind of build we are dealing with when someone requests help (assuming they fill things out properly).
➡️ Optimized the `jar` task in build.xml. We were doing some unnecessary operations there. I changed it to just copy `javascript-source` directly to the output folder `dist/build` instead of needlessly copying it to `resources` just to then be copied to `dist/build` immediately after (albeit in a roundabout way). I also replaced the copying of `dist/build` to `dist/PhantomBot-x.x.x` with doing the same action as a move/rename operation, since there is no reason to then leave the `dist/build` folder just sitting there afterwards.
➡️ Replaced Reflections with an internal class. It seemed like a big dependency (especially when counting that both guava and javassist is required by it) to do something that only takes around 80 lines of easy code to do ourselves
 
:no_entry_sign: Removed/Deprecated:
:arrow_right: Deprecated IniStore. Nobody should be using this anyway
:arrow_right: Removed `DataStore.SaveChangedNow()`. Not used, was an IniStore only method
:arrow_right: Removed `DataStore.ReloadFile(String)`. Not used, was an IniStore only method
:arrow_right: Removed `DataStore.setAutoCommit(boolean)`. Not possible to use with the new Connection pooling. Methods that already do batch operations were set to toggle auto commit directly on their connections if necessary
:arrow_right: Removed old panel in git. It just took up space, if someone needs it they can go back in the Git history
➡️ Removed SocketIOExample and NewPanelSocketServer. They were both unused and were keeping at least 5 dependencies that were otherwise unused in the dependency tree. If someone needs it they can go back in the Git history
:arrow_right: Support for any Java version below 11 is removed
:arrow_right: Support for 32-bit Windows is removed due to no x86 Java 11 version existing for it

:stop_sign: Known Issues:
:arrow_right: Discord4J 3.0.x series removed the class `sx.blah.discord.util.EmbedBuilder`, this has been replaced with the equivalent `tv.phantombot.discord.util.EmbedBuilder`
:arrow_right: Discord4J 3.0.x series replaced `object.getStringID()` with `object.getId().asString()`. This applies to all Discord object types (Channel, Role, Guild, etc)
:arrow_right: Discord4J 3.0.x series replaced `object.mention()` with `object.getMention()`

:globe_with_meridians: Download it:
:arrow_right: This build is based on nightly revision `a4a3150` pushed on `January 6, 2020 @ 10:58 AM EST`
:arrow_right: Edge build  `a614af1` is `RC11` deployed on `January 6, 2020 @ 4:54 PM EST`
:arrow_right: https://github.com/gmt2001/PhantomBot-1/runs/376411865
:arrow_right: Click the `Artifacts` drop-down in the top-right corner
:arrow_right: All artifacts are the same bot. The ones with platform names simply exclude the JRE/launcher script stuff that isn't needed for that platform, to reduce download size
:arrow_right: Download the first artifact, `PhantomBot-edge`, if you want everything for all platforms

:question: Info/FAQs:
:arrow_right: The reason for Java being included with the downloads is that Oracle refuses to provide it to users of Java 9 and up. The only solution they provide is for the developers to include their own trimmed-down version with their program, use OpenJDK, or stay with Java 8. On Linux x86_64, I chose to include the OracleJDK even though OpenJDK is readily available to reduce potential conflict points (differing versions). Since none of this is available from Oracle for x86 or ARM, those platforms will have to use OpenJDK
:arrow_right: Raspberry Pi's running Raspbian 9 (Stretch) will need to either upgrade to Rasbian 10 (Buster) or setup the `stretch-backports` repository in apt. Instructions are available at https://github.com/superjamie/lazyweb/wiki/Raspberry-Pi-Debian-Backports#installation

Debian 9 (Stretch) users will also have to setup the appropriate `stretch-backports` repository in apt
➡️ Special thanks goes to community members [ceriam](https://www.twitch.tv/ceriam) and [TimeO2](https://www.twitch.tv/timeo2) who have been running the bot in production on their channels and providing me with bug reports and feedback

### Apache Ivy Apache Ivy - The agile dependency manager
Apache Ivy is a dependency management system that is designed to integrate seamlessly into `ant` and pulls dependencies from Maven Central, the same source as Maven build scripts.

Using Ivy allows us to easily manage all dependencies and sub-dependencies, as well as update them to newer versions quickly and easily. It eliminates the need for us to manually download and/or compile certain dependencies or sub-dependencies and then distribute them to our core build platforms. As a bonus, by using the `sync` parameter, I have set it up to automatically remove dependencies from the libs folder when they are removed from the dependency tree (either upstream at Maven or by editing ivy.xml).

Ivy is provided in a self-contained jar file that can be JIT downloaded by the `ant` script, so once a developer has set up the appropriate ant tasks in our build.xml file and created the ivy.xml file, it is zero-configuration and zero-installation for all developers for the lifetime of the project.

I have provided the build task `ivy-retrieve` to download the libraries into the lib folder. It has been added into the build chain when running existing build tasks such as `jar`. I have also provided the `ivy-cleancache` task, which will delete all cached copies of the libs (Ivy creates a cache somewhere in your user home folder), and the `ivy-clean-retrieve` task to run `ivy-cleancache` then `ivy-retrieve`, for developers who need to manually add the libs to their IDE's project info for IntelliSense (such as NetBeans).

As an additional feature, Ivy can be commanded to create an HTML or XML file with information on all dependencies for the build, including the dependency tree, sizes, versions, homepages, evicted dependencies (old versions rejected because new versions were included elsewhere), and Licenses for the dependencies (via name and hyperlink to the license text). I have setup Ivy to generate the HTML file and deploy it with the bot as part of the build so we comply with any licensing requirements.

### CODE REVIEW

**Comment by gmt2001** [comment]
### Test report

- [x] Build succeeds on all platforms: https://github.com/gmt2001/PhantomBot-1/runs/254202474
- [x] Bot runs fine on Raspberry Pi
- [x] Make sure there are no uncaught exceptions that can lock up the bot from the updates.
- [x] Make sure discord4j is update to date with the latest stable build. Using Discord4J 3.0.9, latest is 3.0.10, released 3 days ago. Will look into possible update to 3.0.10 if desired.
- [x] Make sure discord4j has support for the new announcement channels. Explicit support is provided for channels of Discord API Type `GUILD_NEWS` which is known in the Discord client as an _Announcement_ channel. This is confirmed working by community member ceriam
- [x] Make sure that updating discord4j didn't break custom scripts. Some scripts may be temporarily broken due to 3 unavoidable changes listed in the first post above, but each issue is a 5 second copy/paste fix.
- [x] Full set of regression tests.
- - [x] Startup
- - [x] Panel
- - [x] module enable/disable
- - [x] addcom
- - [x] setgame/settitle
- - [x] permcom
- - [x] pricecom
- - [x] coolcom
- - [x] followHandler
- - [x] subscribeHandler
- - [x] bitsHandler
- - [x] raidHandler
- - [x] audioPanel
- - [x] noticeSystem
- - [x] pointSystem
- - [x] quoteSystem
- - [x] Discord
- - [x] Persistence

#### Screenshots
Memory usage, idle channel
Annotation 2019-10-09 184406

Web panel working


Title and game were changed by bot command


#### Logs
Logs were taken on a Raspberry Pi 4 with 4GB RAM on Raspbian 10 (Buster) with the latest `openjdk-11-jre-headless` package

Run 1
[PhantomBot-Test.log.txt](https://github.com/PhantomBot/PhantomBot/files/3709701/PhantomBot-Test.log.txt)

Run 2, testing follow handler and persistence
[PhantomBot-Test2.log.txt](https://github.com/PhantomBot/PhantomBot/files/3709699/PhantomBot-Test2.log.txt)

**Comment by gmt2001** [comment]
Merged in Scania's `founder` badge fix from master and updated the edge.yml workflow to support branches starting with the name `edge-`, to allow parallel development. First post updated

**Comment by gmt2001** [comment]
Updated Discord4J to 3.0.11, which is currently the latest

**Comment by DuIslingr** [comment]
Is the launch-service.sh broken on this? i had setup for it to get launched on boot with the official release build then i switched to this and it doesnt seem to work anymore. even launching manually with systemctl doesnt work and it doesnt spit out any errors or anything when running the command. its in the exact same directory and everything and has executable permissions. launching the bot via launch.sh myself works fine though.

Also might I suggest this over normal openjdk as it actually goes through testing. Also provides 32 bit windows editions so you could add that back if you wanted. https://bell-sw.com/

**Comment by gmt2001** [comment]
@Dulslingr Double check that your combination of chown and chmod allows the service user to access all files, including the Java executable in `java-runtime-linux`. Also ensure that the service user is allowed to execute the Java executable. You may want to try `cd PhantomBotDir && sudo chown serviceuser:serviceuser --recursive . && sudo chmod 0744 ./launch-service.sh && sudo chmod 0744 ./java-runtime-linux/bin/java`

Also ensure that you did not mix this build with the release. It should be in it's own separate directory, with only the config and custom scripts copied in

**Comment by BrandenB** [comment]
Merging this since it's been sitting here and it has all the latest fixes for Discord and other important things that don't currently work in the nightly.

**Review by BrandenB — APPROVED** [review]
Merging.

**Pull request merged**
