### PR TITLE
Like a ninja web panel module loading overhaul inc custom module loading

### PR DESCRIPTION
**Pull request by LikeANinja**
I am back with my previous pull request + a little extra. All of these changes are designed to allow easy to plug in and play extensions to the web panel without the need to touch the core web panel code (which is, as you know not quite a simple process to get things in the right places). 

The core of these changes (admittedly not all, but the most important parts) have been running on a live bot for a couple of weeks with no issues (yes... it has taken me a long time to pull my finger out and get the pull request submitted lol)

Anyway here are the changes :D

**resources/web/pane/index.html**
- Cleared the tab list (minus dashboard, audio and information)
- Cleared the tab panels  (minus dashboard, audio and information)
- Added list of scripts under the panels container to pull removed panels back in
- Wrapped existing tab init functions into a buildPanel function

**resources/web/pane/js/audioPanel.js**
- Removed setInterval for doQuery
- Added doQuery and onMessage hooks

**resources/web/panel/js/commandsPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/dashboardPanel.js**
- Removed setInterval for doQuery
- Added doQuery and onMessage hooks

**resources/web/panel/js/discordPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/donationsPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/gamblingPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/gamesPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/globalPanel.js**
- Added onMessage hook

**resources/web/panel/js/greetingsPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/helpPanel.js**
- Removed setInterval for doQuery
- Added doQuery and onMessage hooks

**resources/web/panel/js/hostraidPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/noticesPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/pointsPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/queuePanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/quotesPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/ranksPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/timePanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/twitterPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/viewersPanel.js**
- Removed setInterval for doQuery
- Added panelTab, doQuery and onMessage hooks

**resources/web/panel/js/panelUtils.js**
- Removed hardcoded on message listeners and replaced it with for loops to call appropriate onmessage function
- Replaced performCurrentPanelRefresh hardcoded switch statement with dynamic call to appropriate doQuery function
- Added getActiveTab function to get the currently selected tab
- Added addDoQuery function to add doQuery functions to an array
- Added addOnMessage function to add onMessage functions to an array
- Added addPanelTab function to add html path and tab text to an array
- Added buildPanel function to build the panel using the supplied data by the above 3 functions before calling supplied callback function
- Added loadCustomModules function to automatically load in custom panel javascript files.
- Added temp interval to loop and run all doQueries

**resources/web/panel/custom/readme.js**
- Added readme instructing how to use the new custom folder in the panel

### CODE REVIEW

**Comment by BrandenB** [comment]
I said this in your last pull request, please follow our code style. 

**Issues:**
- Follow our code style.
- The refreshing notice always says `refreshing data` and not the tab name like before.
- The dashboard doesn't automatically refresh data anymore.
- The panel can hang when switching through tabs fast.

That's just with five minutes of testing, I'll let other people do more testing before merging.

**Comment by LikeANinja** [comment]
@ScaniaTV 
Sorry, I did try to stick to your code style, but breaking a habit is hard to do when you do things one way on a daily basis :p I think I have fixed it up, using the beautifier it wants to format a ton of code that is already there, so I have only used that as a base to try and catch everything.

The automatic refreshing should be sorted, I herpa derped and forgot to fix something on a code rewrite  🤦‍♂️ 

I haven't been able to get any panel hanging :/ 🤷‍♂️ 

As for the `refreshing data` I personally didn't see it as a problem. The current build only shows the name of the panel on auto data refresh, not forced (that shows `refreshing data`), so I decided not to worry about it as it will only ever be refreshing the current panel. I will add if it really has to be there :)

**Comment by BrandenB** [comment]
Looks good, I still see some code style issues though. Other than that everything seems fine, I will talk with @IllusionaryOne about it once he comes back. :)

**Comment by IllusionaryOne** [comment]
Not sure how I dropped this one on the floor.  If it has no conflicts and @ScaniaTV is happy, I'm happy.

I suppose this would be grandfathered in not requiring test results and I think Scania already reviewed it?  We might need to make sure that the files weren't changed between the time this PR came in and we go to merge it as I often worry about the auto-merge feature of git.

**Comment by CreativeCodeCat** [comment]
@IllusionaryOne I know sub gifting was added after this pull came in so I dont know what effect that will have

**Comment by LikeANinja** [comment]
Why hello @IllusionaryOne ! It has been a while since this PR was submitted and there have been quite a few changes across the board on PB, I was regularly testing it up until about the end of last year when I had a moment, but the last month or so has been hectic for me and I haven't had much time to spare (adult like hey :( ). I will make sure I pull in all the latest changes and run more tests (I have a couple of bots that are in need of updating using this panel anyway). If you want test results, how do you want them? screenshots of a working dash? network timings? Let me know and I will do my best to supply.

@AlixeAtTwitch Theoretically there shouldn't be any effect, but as I said above I haven't been able to touch it recently :( so cannot say for sure. Although I'm not sure when the sub gifting was implemented, so I might have unknowingly tested it already with no issues XD

**Comment by gmt2001** [comment]
Screenshots of a working dash will probably do. Also try running a command from the dash that makes the bot respond in chat, like opening a raffle then entering it, and show a screenshot of both the raffle dash showing your entry and the chat where the bot responded.

**Comment by IllusionaryOne** [comment]
Should I close this for now and expect a new PR?  Or leave this one open?  I am good either way.

**Comment by LikeANinja** [comment]
Sorry, life has just been pulling my attention left right and center all of a sudden -.- I shall close and open a new request in due course 👍

**Comment by IllusionaryOne** [comment]
You do not have to tell me twice about life being busy, same here!  Thanks for all that you do.

Cheers!

**Pull request closed without merging**
