### PR TITLE
!quotemodetoggle

### PR DESCRIPTION
**Pull request by lbarnett83**
1.  Created the !quotemodetoggle command, which allows switching between "!addquote [quote]" and "!addquote [user] [quote]" functionality
2. Re-wrote the addquote function to respect the quoteMode variable.
3. Made the !quotemodetoggle command write changes out to the DB

quoteMode defaults to "!addquote [quote]" if quoteMode doesn't exist in the settings DB

### CODE REVIEW

**Comment by BrandenB** [comment]
You're missing a `)` at the end of `getSetIniDbBoolean`

**Comment by lbarnett83** [comment]
And of course by the time this is caught, I'm 2 hours from home. I'll fix it and re-commit as soon as I get home. :)  Cheers Scania, must be nice not to be the only one making typos. ;)

**Comment by BrandenB** [comment]
So this is fully tested with no bugs?

**Comment by lbarnett83** [comment]
I've tested it by switching modes, using !addquote with each mode active, and reviewed the quote getting stored under each mode. I've also shut down and reloaded the bot with each mode active to ensure that mode stays active on a reboot of the bot. If you can think of anything else to test, let me know. Cheers.

**Comment by BrandenB** [comment]
should be fine. Merging.

**Pull request merged**
