### PR TITLE
Bugfix/dockerfile java bash

### PR DESCRIPTION
**Pull request by ZyanKLee**
Hello PhantomBot developers,

I use this great piece of work with docker-compose and had few small issues with it.
This PR fixes them and also applies the option to build the image locally.

* Dockerfile: CMD needs `bash` instead of `sh` as the latter does not support `[[`
* Dockerfile: `./java-runtime-linux/bin/java` was missing `+x` flag and could therefore not be executed
* docker-compose.yml: added commented block to enable a local build of the docker image

Test results:

```
$ docker-compose logs -f
Attaching to phantombot-nightly
phantombot-nightly | [06-30-2020 @ 07:23:59.093 GMT] The working directory is: /opt/PhantomBot
phantombot-nightly | [06-30-2020 @ 07:23:59.169 GMT] Detected Java 11.0.4 running on Linux 5.4.0-39-generic (amd64)
phantombot-nightly | [06-30-2020 @ 07:23:59.187 GMT] 
phantombot-nightly | [06-30-2020 @ 07:23:59.198 GMT] PhantomBot Version: 3.2.0 (stable)
phantombot-nightly | [06-30-2020 @ 07:23:59.199 GMT] Build Revision: 7eb646fc
phantombot-nightly | [06-30-2020 @ 07:23:59.199 GMT] Creator: mast3rplan
phantombot-nightly | [06-30-2020 @ 07:23:59.199 GMT] Developers: PhantomIndex, Kojitsari, ScaniaTV, Zackery (Zelakto) & IllusionaryOne
phantombot-nightly | [06-30-2020 @ 07:23:59.199 GMT] https://phantombot.tv/
phantombot-nightly | [06-30-2020 @ 07:23:59.200 GMT] 
phantombot-nightly | [06-30-2020 @ 07:24:00.415 GMT] 
phantombot-nightly | [06-30-2020 @ 07:24:00.682 GMT] Validated Twitch CHAT (oauth) OAUTH Token.
phantombot-nightly | [06-30-2020 @ 07:24:00.694 GMT] Validated Twitch API (apioauth) OAUTH Token.
phantombot-nightly | [06-30-2020 @ 07:24:01.200 GMT] Loaded module: core/misc.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:01.212 GMT] Loaded module: core/jsTimers.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:01.369 GMT] Loaded module: core/updates.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:01.598 GMT] Loaded module: core/chatModerator.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:01.619 GMT] Loaded module: core/fileSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.040 GMT] Loaded module: core/lang.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.050 GMT] Loaded module: core/commandPause.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.075 GMT] Loaded module: core/logging.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.088 GMT] Loaded module: core/commandRegister.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.100 GMT] Loaded module: core/whisper.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.126 GMT] Loaded module: core/commandCoolDown.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.131 GMT] Connected to Discord, finishing authentication...
phantombot-nightly | [06-30-2020 @ 07:24:02.139 GMT] Loaded module: core/keywordCoolDown.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.158 GMT] Loaded module: core/gameMessages.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.180 GMT] Loaded module: core/patternDetector.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.234 GMT] [ERROR] [lambda$connect$4()@DiscordAPI.java:151] Discord rejected privileged intents (4014 Disallowed intent(s).). Trying without them...
phantombot-nightly | [06-30-2020 @ 07:24:02.253 GMT] Loaded module: core/permissions.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.277 GMT] Loaded module: core/streamInfo.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.307 GMT] Loaded module: core/timeSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.339 GMT] Loaded module: core/initCommands.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.363 GMT] Loaded module: core/panelCommands.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.388 GMT] Loaded module: handlers/donationHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.412 GMT] Loaded module: handlers/tipeeeStreamHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.471 GMT] Loaded module: handlers/subscribeHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.496 GMT] Loaded module: handlers/raidHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.506 GMT] Loaded module: handlers/gameScanHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.547 GMT] Loaded module: handlers/twitterHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.568 GMT] Loaded module: handlers/hostHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.579 GMT] Loaded module: handlers/dataServiceHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.598 GMT] Loaded module: handlers/followHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.610 GMT] Loaded module: handlers/clipHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.620 GMT] Loaded module: handlers/wordCounter.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.637 GMT] Loaded module: handlers/keywordHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.655 GMT] Loaded module: handlers/streamElementsHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.675 GMT] Loaded module: handlers/bitsHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.698 GMT] Loaded module: handlers/emotesHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.710 GMT] Loaded module: commands/highlightCommand.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.726 GMT] Loaded module: commands/dualstreamCommand.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.740 GMT] Loaded module: commands/topCommand.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.751 GMT] Loaded module: commands/streamCommand.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.764 GMT] Loaded module: commands/deathctrCommand.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.773 GMT] Loaded module: commands/nameConverter.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.782 GMT] Loaded module: commands/lastseenCommand.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.873 GMT] Loaded module: commands/customCommands.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.887 GMT] Loaded module: games/slotMachine.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.896 GMT] Loaded module: games/killCommand.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.904 GMT] Loaded module: games/random.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.910 GMT] Loaded module: games/8ball.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.920 GMT] Loaded module: games/gambling.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.929 GMT] Loaded module: games/roll.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.951 GMT] Loaded module: games/adventureSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.959 GMT] Loaded module: games/roulette.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.974 GMT] Loaded module: systems/ticketraffleSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:02.986 GMT] Loaded module: systems/commercialSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.016 GMT] Loaded module: systems/pointSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.036 GMT] Loaded module: systems/raffleSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.046 GMT] Loaded module: systems/auctionSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.060 GMT] Loaded module: systems/quoteSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.068 GMT] Loaded module: systems/cleanupSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.080 GMT] Loaded module: systems/audioPanelSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.096 GMT] Loaded module: systems/queueSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.171 GMT] Loaded module: systems/youtubePlayer.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.185 GMT] Loaded module: systems/noticeSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.199 GMT] Loaded module: systems/pollSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.215 GMT] Loaded module: systems/bettingSystem.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.227 GMT] Loaded module: systems/ranksSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.236 GMT] Loaded module: systems/greetingSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.252 GMT] Loaded module: discord/core/misc.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.260 GMT] Loaded module: discord/core/accountLink.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.265 GMT] Loaded module: discord/core/patternDetector.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.290 GMT] Loaded module: discord/core/moderation.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.300 GMT] Loaded module: discord/core/registerCommand.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.310 GMT] Loaded module: discord/core/commandCooldown.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.320 GMT] Loaded module: discord/core/roleManager.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.334 GMT] Loaded module: discord/handlers/tipeeeStreamHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.349 GMT] Loaded module: discord/handlers/subscribeHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.357 GMT] Loaded module: discord/handlers/twitterHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.368 GMT] Loaded module: discord/handlers/hostHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.378 GMT] Loaded module: discord/handlers/followHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.387 GMT] Loaded module: discord/handlers/streamlabsHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.397 GMT] Loaded module: discord/handlers/clipHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.405 GMT] Loaded module: discord/handlers/keywordHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.421 GMT] Loaded module: discord/handlers/streamElementsHandler.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.447 GMT] Loaded module: discord/handlers/streamHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.459 GMT] Loaded module: discord/handlers/bitsHandler.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.487 GMT] Loaded module: discord/commands/customCommands.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.494 GMT] Loaded module: discord/games/kill.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.503 GMT] Loaded module: discord/games/slotMachine.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.509 GMT] Loaded module: discord/games/random.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.514 GMT] Loaded module: discord/games/8ball.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.524 GMT] Loaded module: discord/games/gambling.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.532 GMT] Loaded module: discord/games/roll.js (Disabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.538 GMT] Loaded module: discord/games/roulette.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.545 GMT] Loaded module: discord/systems/pointSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.566 GMT] Loaded module: discord/systems/promoteSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.577 GMT] Loaded module: discord/systems/greetingsSystem.js (Enabled)
phantombot-nightly | [06-30-2020 @ 07:24:03.608 GMT] 
phantombot-nightly | [06-30-2020 @ 07:24:03.609 GMT] For support please visit: https://community.phantombot.tv
phantombot-nightly | [06-30-2020 @ 07:24:03.609 GMT] 
phantombot-nightly | [06-30-2020 @ 07:24:03.628 GMT] Connecting to Twitch WS-IRC Server (SSL) [irc-ws.chat.twitch.tv]
phantombot-nightly | [06-30-2020 @ 07:24:04.462 GMT] Connected to botname@irc-ws.chat.twitch.tv (SSL)
phantombot-nightly | [06-30-2020 @ 07:24:04.713 GMT] Channel Joined [#channelname]
phantombot-nightly | [06-30-2020 @ 07:24:04.937 GMT] botname ready!
phantombot-nightly | [06-30-2020 @ 07:24:05.123 GMT] Connected to Twitch Host Data Feed
phantombot-nightly | [06-30-2020 @ 07:24:10.414 GMT] Connected to Discord, finishing authentication...
phantombot-nightly | [06-30-2020 @ 07:24:10.583 GMT] Successfully authenticated with Discord.
phantombot-nightly | [06-30-2020 @ 07:24:24.927 GMT] >> Enabling follower announcements
phantombot-nightly | [06-30-2020 @ 07:24:25.126 GMT] >> Enabling hosts announcements
```

### CODE REVIEW

**Review by gmt2001 — CHANGES_REQUESTED** [review]
We don't use ports 25003 or 25004

**Comment by ZyanKLee** [comment]
I'm confused. I'll check why I added them and will get back to you with a fixed PR.

**Comment by ZyanKLee** [comment]
There, I removed those ports. Still confused, but that is my problem :-D

**Comment by gmt2001** [comment]
I just noticed that we weren't chmoding launch-service.sh either. Was it working fine without that when you tested?

**Comment by ZyanKLee** [comment]
That is not a problem as the Dockerfile defines the CMD as `bash launch-service.sh`. Execution permission would be needed if you would execute it by itself. i.e. `./launch-service.sh` or `/path/to/launch-service.sh` without the explicit interpreter.

**Review by gmt2001 — APPROVED** [review]

**Pull request merged**
