### PR TITLE
RepoVersion getting from Manifest.mf info

### PR DESCRIPTION
**Pull request by stachu540**
`RepoVersion.java` - for many attempts and test's this class now getting information about package from the MANIFEST file.
Also... there is changes about nightly build states. Now it is a boolean state. **Default is false**.

Ill leave this for reviewing and testing it.

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
Issues:

1) pre.compile:
     [echo] PhantomBot Version 2.3.6.1 (49f9a54) (true)
     [echo] PhantomBot Control Panel Version 1.1

That shouldn't say (true) I have tools that depend on seeing that is nightly on my build server.  Generally, do not change text in a build process.

2) /* astyle --style=java --indent=spaces=4 */

Didn't check beyond that.

**Comment by stachu540** [comment]
`RepoVersion.java` - Code reformatted into the 4 spaces. (I love working on 2)
`build.xml` - added another one condition - now is not boolean word. It will be `nightly_build` or `not_nightly`.

Also i work on maven script for this repo. I need some coppule test's and changes. If you are interest change compiler I work for this stuff [here](https://github.com/stachu540/PhantomBot_Maven).

**Comment by IllusionaryOne** [comment]
Will review later today.  Would not go with Maven.  For one:

    <dependency>
      <groupId>org.java-websocket</groupId>
      <artifactId>java-websocket</artifactId>
      <version>1.3.3</version> 
    </dependency>

I have had to make modifications and we use a specialized version of this library, the latest version there has even worse problems when I tested it.  There are bugs with SSL handling.  

Same goes for other directives in there, going to versions that we have tested out and have problems on a large scale would not be desired.

Good work though!

**Comment by stachu540** [comment]
Well, I don't know mate 🤷‍♂️ . You are developers. It is up to you. I just getting fun for doing this, and getting some knowledge about it. 😄 

By the way. Merge is ready to other test's and pulls. For now... it is looks good, if you ask for it.

Very important thing❗️ If try some changes on Manifest file, it will be affect whole project (maybe not not all). but only in `jar` file. Be sure, if everything is fine. Otherwise, I'll close this pull request. I have too much work for other projects.

Thanks for the advice IO. 👍

**Comment by BrandenB** [comment]
I'm with IllusionaryOne with Maven, some of the libraries we use are probably really outdated, some are modified, meaning if we update them we will have to change some of the bot's code.

I will merge this change for now though.

**Comment by BrandenB** [comment]
I will be reverting these changes since it seems to not work for some users.

More information is available here: https://community.phantombot.tv/t/phantombot-2-3-7-1-update-issue/327/11

**Comment by stachu540** [comment]
If Manifest doesn't exists, it will throw exception and returning null. I don't get it why he is return null and doesn't throw `NullPointException`?

I'll investigate it, for those reason. By the way, **reverting changes is a final option**.

**Comment by IllusionaryOne** [comment]
I reverted the change last night, and that worked for the user.  Still not entirely sure why this is the case, the code seems solid, but, for now, as the previous way is essentially foolproof, going with that for right now.

**Pull request merged**
