### PR TITLE
Web Panel Module Loading

### PR DESCRIPTION
**Pull request by LikeANinja**
Reworked web panel to use a hook system to load in bot modules making the web panel a lot more flexible with the loading of panels and adding additional functionality to the web panel.

**resources/web/panel/index.html**
-Stripped out all hardcoded tabs and panels
-Added method call to tabs activate to load in tabs from hooks
-Moved script inclusion tags under #tabs

**resources/web/panel/js/audioPanel.js**
-Stripped hard coded doQuery block
-Added addDoQuery and addOnMessage hook calls

**resources/web/panel/js/commandsPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/dashboardPanel.js**
-Stripped hard coded doQuery block
-Added addDoQuery and addOnMessage hook calls

**resources/web/panel/js/discord.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/donations.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/gambling.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/games.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/globalPanel.js**
-Added addOnMessage hook call

**resources/web/panel/js/greetings.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/helpPanel.js**
-Stripped hard coded requestVersoin block
-Added  addDoQuery and addOnMessage hook calls

**resources/web/panel/js/hostraidPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/keywordsPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/moderationPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/noticesPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/panelUtils.js**
-Replaced connection.onmessage if block with for loop to loop around an array of onMessage calls
-Replaced performCurrentPanelRefresh method functionality to no longer rely on hard coded tab ids, instead using checking data-phantombot-tab to determine the appropriate doQuery call
-Added addDoQuery method to add in doQuery functions and timeout times to an array, used to call the appropriate doQuery function in performCurrentPanelRefresh
-Added addOnMessage method to add onMessage functions to an array, used in connection.onmessage event
-Added getActiveTab method to return the appropriate tab active tab data
-Added addPanelTab method to store a list of tabs, panels, HTML path and position data to be used on buildPanel method
-Added buildPanel method to loop the stored panel array to render all required tabs and panels in a specified order
   Moved initial on load doQuery call to this file and calling performCurrentPanelRefresh

**resources/web/panel/js/pointsPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/pollPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/queuePanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/quotesPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/ranksPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/timePanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/twitterPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

**resources/web/panel/js/viewersPanel.js**
-Stripped hard coded doQuery block
-Added addPanelTab, addDoQuery and addOnMessage hook calls

### CODE REVIEW

**Comment by IllusionaryOne** [comment]
Brought down this branch to my local, wiped my current web/ area and replaced it, the Panel no longer functions, just stuck at the loading spinner:

Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
2jquery-ui.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.flot.min.js:7 Uncaught ReferenceError: jQuery is not defined
    at jquery.flot.min.js:7
footable.min.js:8 Uncaught ReferenceError: jQuery is not defined
    at footable.min.js:8
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
dateFormat.js:478 Uncaught ReferenceError: jQuery is not defined
    at dateFormat.js:478
disablePanel.js:247 Uncaught ReferenceError: $ is not defined
    at disablePanel.js:247
    at disablePanel.js:248
games.js:1 Uncaught ReferenceError: $ is not defined
    at games.js:1
panelUtils.js:132 Uncaught ReferenceError: $ is not defined
    at newPanelAlert (panelUtils.js:132)
    at a.connection.onopen (panelUtils.js:71)
    at HTMLDivElement.<anonymous> (reconnectingWS.min.js:30)
    at WebSocket.h.onopen (reconnectingWS.min.js:30)
panel:72 Uncaught ReferenceError: $ is not defined
    at panel:72
dashboardPanel.js:627 Uncaught ReferenceError: $ is not defined
    at dashboardPanel.js:627
    at dashboardPanel.js:659
audioPanel.js:412 Uncaught ReferenceError: $ is not defined
    at audioPanel.js:412
    at audioPanel.js:452
helpPanel.js:67 Uncaught ReferenceError: $ is not defined
    at helpPanel.js:67
    at helpPanel.js:75
pointsPanel.js:467 Uncaught ReferenceError: $ is not defined
    at pointsPanel.js:467
    at pointsPanel.js:481
twitterPanel.js:293 Uncaught ReferenceError: $ is not defined
    at twitterPanel.js:293
    at twitterPanel.js:298
queuePanel.js:114 Uncaught ReferenceError: $ is not defined
    at queuePanel.js:114
    at queuePanel.js:117
gamesPanel.js:410 Uncaught ReferenceError: $ is not defined
    at gamesPanel.js:410
    at gamesPanel.js:423
gamblingPanel.js:475 Uncaught ReferenceError: $ is not defined
    at gamblingPanel.js:475
    at gamblingPanel.js:495
hostraidPanel.js:306 Uncaught ReferenceError: $ is not defined
    at hostraidPanel.js:306
    at hostraidPanel.js:320
pollPanel.js:142 Uncaught ReferenceError: $ is not defined
    at pollPanel.js:142
    at pollPanel.js:147
keywordsPanel.js:265 Uncaught ReferenceError: $ is not defined
    at keywordsPanel.js:265
    at keywordsPanel.js:276
quotesPanel.js:212 Uncaught ReferenceError: $ is not defined
    at quotesPanel.js:212
    at quotesPanel.js:219
noticesPanel.js:216 Uncaught ReferenceError: $ is not defined
    at noticesPanel.js:216
    at noticesPanel.js:225
donationsPanel.js:184 Uncaught ReferenceError: $ is not defined
    at donationsPanel.js:184
    at donationsPanel.js:187
greetingsPanel.js:571 Uncaught ReferenceError: $ is not defined
    at greetingsPanel.js:571
    at greetingsPanel.js:576
ranksPanel.js:249 Uncaught ReferenceError: $ is not defined
    at ranksPanel.js:249
    at ranksPanel.js:259
viewersPanel.js:379 Uncaught ReferenceError: $ is not defined
    at viewersPanel.js:379
    at viewersPanel.js:384
timePanel.js:311 Uncaught ReferenceError: $ is not defined
    at timePanel.js:311
    at timePanel.js:319
moderationPanel.js:923 Uncaught ReferenceError: $ is not defined
    at moderationPanel.js:923
    at moderationPanel.js:939
commandsPanel.js:682 Uncaught ReferenceError: $ is not defined
    at commandsPanel.js:682
    at commandsPanel.js:706
discordPanel.js:415 Uncaught ReferenceError: $ is not defined
    at discordPanel.js:415
    at discordPanel.js:426
panelUtils.js:461 Uncaught ReferenceError: $ is not defined
    at buildPanel (panelUtils.js:461)
    at panel:137
globalPanel.js:190 Uncaught ReferenceError: $ is not defined
    at globalPanel.js:190
    at globalPanel.js:193
panel:155 Uncaught ReferenceError: $ is not defined
    at panel:155
panel:170 Uncaught ReferenceError: $ is not defined
    at panel:170
logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-ui.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by IllusionaryOne** [comment]
I did remember something, my guess is you didn't have the latest master branch, check out this merge from August 24:
https://github.com/PhantomBot/PhantomBot/commit/165ee7ea0d8c368ae19455f65c30bea7f079c6a1

Some files got moved around.

That said, there have been other fixes and adjustments.  I am curious what all might get lost and not automerged from the Panel if you worked from a fairly old version.  Can you verify which branch/commit you performed this work from?

**Comment by LikeANinja** [comment]
I initially cloned the repo and branched from commit 26c7b26 (16 Aug). I have then worked from that branch and making sure any changes that were committed to the master were pulled into my branch.

Looking at the commit history, some of the changes made on that stated commit do not appear in my history. One of those changes being the location change of the assets. This has clearly caused my source copy to be bent all out of shape :/

This may be where the issue is. I will start again from the latest commit and resubmit the pull request

**Comment by BrandenB** [comment]
Another thing that @IllusionaryOne forgot to mention, please be sure to follow our code style. Also, after fixing the issue myself, I noticed that the panel was loaded a bit slower than normal. I didn't read the whole code, but be sure this doesn't impact the panel's performance. 

Thanks!

**Pull request closed without merging**
